import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "vi" | "en";

const translations = {
  vi: {
    // Navbar
    home: "Trang chủ",
    jobs: "Việc làm",
    login: "Đăng nhập",
    register: "Đăng ký",
    aiSuggestions: "Gợi ý việc",
    profile: "Hồ sơ",
    cvVault: "Tủ hồ sơ/CV",
    applications: "Đơn ứng tuyển",
    recruiterRegister: "Đăng ký Recruiter",
    aiCandidates: "Gợi ý ứng viên",
    dashboard: "Bàn tuyển dụng",
    adminMenu: "Menu Admin",
    logout: "Đăng xuất",

    // HomePage
    heroTag: "Nền tảng tuyển dụng thông minh #1 Việt Nam",
    heroTitle1: "Tìm việc làm",
    heroTitle2: "mơ ước của bạn",
    heroDesc: "Kết nối ứng viên tài năng với nhà tuyển dụng uy tín. AI thông minh gợi ý công việc phù hợp nhất với hồ sơ của bạn.",
    startFree: "Bắt đầu miễn phí",
    toDashboard: "Đến Bàn tuyển dụng",
    toAdminMenu: "Menu Admin",
    findJobNow: "Tìm việc ngay",
    searchJobs: "Tìm kiếm việc làm",
    searchPlaceholder: "Tìm kiếm vị trí, công ty, kỹ năng...",
    search: "Tìm kiếm",
    statJobs: "Tin tuyển dụng",
    statCandidates: "Ứng viên đăng ký",
    statCompanies: "Công ty đối tác",
    statSuccess: "Tỷ lệ tuyển thành công",
    latestJobs: "Việc làm mới nhất",
    latestJobsDesc: "Cơ hội tuyển dụng đang mở từ các công ty hàng đầu",
    viewAll: "Xem tất cả",
    forYou: "Dành riêng cho bạn",
    forYouDesc: "NextJob phục vụ mọi đối tượng với những công cụ được thiết kế đặc biệt",
    forCandidate: "Dành cho Ứng viên",
    forCandidateDesc: "Tạo hồ sơ chuyên nghiệp, tải CV và nhận gợi ý việc làm phù hợp từ AI. Theo dõi trạng thái đơn ứng tuyển realtime.",
    viewMyProfile: "Xem hồ sơ",
    forRecruiter: "Dành cho Nhà tuyển dụng",
    forRecruiterDesc: "Đăng tin tuyển dụng, duyệt đơn ứng viên và nhận gợi ý ứng viên phù hợp từ AI. Quản lý toàn bộ quy trình tuyển dụng.",
    registerRecruiter: "Đăng ký Recruiter",
    forAdmin: "Dành cho Quản trị viên",
    forAdminDesc: "Phê duyệt đơn đăng ký nhà tuyển dụng, quản lý tài khoản và giám sát hoạt động toàn hệ thống.",
    accessAdmin: "Truy cập Admin",
    ctaTitle: "Sẵn sàng bắt đầu?",
    ctaDesc: "Tham gia cùng hàng nghìn ứng viên và nhà tuyển dụng đang sử dụng NextJob",
    registerFree: "Đăng ký miễn phí",
    footerDesc: "Nền tảng tuyển dụng thông minh.",

    // Job card / list
    viewDetail: "Xem chi tiết",
    save: "Lưu",
    unsave: "Bỏ lưu",
    active: "Đang tuyển",
    expired: "Hết hạn",
    deadline: "Hạn nộp",
    postedOn: "Đăng ngày",
    salary: "Thỏa thuận",
    noResult: "Không tìm thấy kết quả",
    noResultDesc: "Thử điều chỉnh từ khóa hoặc bộ lọc của bạn",
    clearFilters: "Xóa bộ lọc",
    filterType: "Loại hình",
    filterLocation: "Địa điểm",
    allLocations: "Tất cả địa điểm",
    savedOnly: "Đã lưu",
    jobCount: (active: number, total: number) => `${active} tin đang tuyển / ${total} tổng tin`,

    // Common
    loading: "Đang tải...",
    cancel: "Hủy",
    save_btn: "Lưu",
    confirm: "Xác nhận",
    delete: "Xóa",
    edit: "Sửa",
    add: "Thêm",
    back: "Quay lại",
    submit: "Nộp",
    close: "Đóng",

    // Auth
    welcomeBack: "Chào mừng trở lại",
    loginDesc: "Đăng nhập để tiếp tục hành trình tìm việc",
    demoAccounts: "Tài khoản demo (mật khẩu: password123)",
    email: "Email",
    password: "Mật khẩu",
    loggingIn: "Đang đăng nhập...",
    loginBtn: "Đăng nhập",
    noAccount: "Chưa có tài khoản?",
    registerNow: "Đăng ký ngay",
    createAccount: "Tạo tài khoản",
    registerDesc: "Đăng ký miễn phí, bắt đầu hành trình của bạn",
    fullName: "Họ và tên",
    minPassword: "Tối thiểu 8 ký tự",
    registering: "Đang đăng ký...",
    registerBtn: "Đăng ký",
    hasAccount: "Đã có tài khoản?",
    loginLink: "Đăng nhập",
    registerSuccess: "Đăng ký thành công!",
    redirectingProfile: "Đang chuyển đến trang hồ sơ...",
    pwWeak: "Yếu", pwMedium: "Trung bình", pwStrong: "Mạnh",
    loginError: "Email hoặc mật khẩu không đúng. Vui lòng thử lại.",
    registerError: "Email này đã được đăng ký. Vui lòng dùng email khác.",

    // Profile
    profileTitle: "Hồ sơ",
    personalInfo: "Thông tin cá nhân",
    phone: "Điện thoại",
    avatarUrl: "URL ảnh đại diện",
    avatarTitle: "Ảnh đại diện",
    uploadAvatar: "Tải ảnh lên",
    changeAvatar: "Đổi ảnh",
    removeAvatar: "Gỡ ảnh",
    avatarHint: "Hỗ trợ JPG, PNG, WEBP — tối đa 2MB",
    avatarUploadSuccess: "Đã cập nhật ảnh đại diện!",
    avatarRemoveSuccess: "Đã gỡ ảnh đại diện!",
    uploadingAvatar: "Đang tải ảnh lên...",
    savingProfile: "Đang lưu...",
    saveInfo: "Lưu thông tin",
    saved: "Đã lưu!",
    profileItems: "Dòng hồ sơ",
    addItem: "Thêm dòng",
    noItems: "Chưa có dòng hồ sơ nào. Thêm thông tin để tạo CV dễ dàng hơn!",
    itemType: "Loại",
    itemTitle: "Tiêu đề",
    itemContent: "Nội dung",
    deleteItemTitle: "Xóa dòng hồ sơ",
    deleteItemMsg: "Bạn có chắc muốn xóa dòng hồ sơ này không?",
    editItemTitle: "Chỉnh sửa dòng hồ sơ",
    editItem: "Sửa dòng",
    saveChanges: "Lưu thay đổi",
    savingChanges: "Đang lưu...",
    updatedItemSuccess: "Đã cập nhật dòng hồ sơ!",
    userManagement: "Quản lý người dùng (Admin)",

    // CV Vault
    cvVaultTitle: "Tủ hồ sơ/CV",
    cvCount: (n: number) => `${n} CV đang lưu`,
    buildCV: "Tạo CV",
    createCV: "Tạo CV",
    uploadCV: "Tải lên",
    uploadHint: "Hỗ trợ PDF, DOC, DOCX — tối đa 10MB",
    cvName: "Đặt tên cho CV...",
    noCV: "Chưa có CV nào",
    noCVDesc: "Tải lên hoặc tạo CV tự động từ hồ sơ",
    uploadBtn: "Tải lên",
    uploadSuccess: "Tải lên thành công!",
    setDefault: "Đặt làm mặc định",
    openFile: "Mở file",
    defaultBadge: "Mặc định",
    appsUsing: (n: number) => `${n} đơn ứng tuyển`,
    unused: "Chưa dùng",
    deleteCVTitle: "Xóa CV",
    deleteCVMsg: "Bạn có chắc muốn xóa CV này? Hành động này không thể hoàn tác.",
    deleteCVBtn: "Xóa CV",

    // Applications
    myApplications: "Đơn ứng tuyển của tôi",
    noApps: "Chưa có đơn ứng tuyển nào",
    noAppsDesc: "Tìm việc và nộp đơn để theo dõi tại đây",
    findJobs: "Tìm việc làm",
    submittedOn: "Nộp",
    progress: "Tiến trình đơn",
    withdrawApp: "Rút đơn",
    withdrawTitle: "Rút đơn ứng tuyển",
    withdrawMsg: "Bạn có chắc chắn muốn rút đơn ứng tuyển này? Hành động này không thể hoàn tác.",
    withdrawBtn: "Rút đơn",

    // Job detail
    backToJobs: "Việc làm",
    applyNow: "Ứng tuyển ngay",
    selectCV: "Chọn CV",
    coverLetter: "Thư giới thiệu",
    coverLetterOpt: "(tùy chọn)",
    coverLetterPlaceholder: "Giới thiệu bản thân và lý do bạn phù hợp với vị trí này...",
    submitting: "Đang nộp...",
    applyBtn: "Nộp đơn",
    applySuccess: "Nộp đơn thành công!",
    applySuccessDesc: "Nhà tuyển dụng sẽ liên hệ bạn sớm.",
    myAppsLink: "Xem đơn của tôi",
    alreadyApplied: "Đã nộp đơn",
    appliedOn: "Ngày nộp",
    appliedCV: "CV",
    toMyApps: "Đến Đơn của tôi",
    noCV_apply: "Bạn chưa có CV. Tải CV lên để ứng tuyển.",
    toCVVault: "Đến Tủ hồ sơ/CV",
    expiredJob: "Hết hạn nộp đơn",
    expiredDesc: "Tin tuyển dụng này đã hết hạn.",
    loginToApply: "Đăng nhập để ứng tuyển vị trí này",
    jobDesc: "Mô tả công việc",
    requirements: "Yêu cầu",
    benefits: "Phúc lợi",
    aboutCompany: "Về",
    similarJobs: "Việc tương tự",
    location: "Địa điểm",
    salaryLabel: "Mức lương",
    deadlineLabel: "Hạn nộp",

    // AI Suggestions
    aiJobTitle: "Gợi ý việc làm AI",
    aiJobDesc: "Được cá nhân hóa theo hồ sơ của bạn",
    aiWelcome: "Xin chào! Tôi là trợ lý AI của NextJob 👋\nTôi có thể giúp bạn tìm những công việc phù hợp nhất dựa trên hồ sơ của bạn. Hãy hỏi tôi hoặc nhấn chip gợi ý bên dưới!",
    chipSuggest: "Gợi ý việc phù hợp",
    chipRemote: "Việc remote lương cao",
    chipHanoi: "Việc tại Hà Nội",
    chatPlaceholder: "Nhắn tin với AI...",
    viewJob: "Xem tin",
    match: (n: number) => `${n}% phù hợp`,

    // Recruiter register
    recruiterTitle: "Đăng ký Nhà tuyển dụng",
    recruiterDesc: "Điền thông tin công ty để được phê duyệt bởi Admin",
    companyName: "Tên công ty",
    companyNameReq: "Tên công ty là bắt buộc.",
    companyEmail: "Email công ty",
    website: "Website công ty",
    licenseUrl: "Đường dẫn giấy phép kinh doanh",
    sendApp: "Gửi đơn đăng ký",
    sending: "Đang gửi...",
    sentSuccess: "Đã gửi đơn!",
    sentSuccessDesc: "Admin sẽ xem xét và phản hồi trong vòng 1-2 ngày làm việc.",
    backHome: "Về trang chủ",
    alreadyRecruiter: "Bạn đã là Nhà tuyển dụng",
    alreadyRecruiterDesc: "Truy cập Bàn tuyển dụng để quản lý tin đăng và đơn ứng viên.",
    toDashboard2: "Đến Bàn tuyển dụng",
    pendingApp: "Đơn đăng ký đang chờ xét duyệt",
    rejectNote: "Lý do từ chối",
    adminNote: "Ghi chú từ Admin",

    // Dashboard
    dashboardTitle: "Bàn tuyển dụng",
    jobListTitle: "Tin tuyển dụng",
    createJob: "Tạo tin",
    noJobs: "Chưa có tin nào",
    jobTitle: "Tiêu đề",
    jobDesc2: "Mô tả công việc",
    creating: "Đang tạo...",
    createBtn: "Tạo tin",
    selectJobHint: "Chọn một tin tuyển dụng để xem đơn ứng viên",
    noApplicants: "Chưa có ứng viên nào nộp đơn",
    update: "Cập nhật",
    newStatus: "Trạng thái mới",
    noteLabel: "Ghi chú",
    notePlaceholder: "Ghi chú (tùy chọn)",

    // AI Candidates
    aiCandTitle: "Gợi ý ứng viên AI",
    aiCandDesc: "Tìm ứng viên phù hợp nhất cho vị trí của bạn",
    selectJob: "-- Chọn tin tuyển dụng --",
    chipCandSuggest: "Gợi ý ứng viên phù hợp",
    chipRankScore: "Xếp hạng theo điểm",
    candPlaceholder: "Nhắn tin với AI...",
    selectJobFirst: "Chọn tin tuyển dụng trước",
    viewCV: "Xem CV",
    noCV_job: "Chưa có CV nộp cho vị trí này.",

    // Admin
    adminTitle: "Duyệt đăng ký Recruiter",
    adminDesc: "Xem xét và phê duyệt đơn đăng ký nhà tuyển dụng",
    pending: "Chờ duyệt",
    approved: "Đã phê duyệt",
    rejected: "Đã từ chối",
    searchAdmin: "Tìm theo công ty, email, người nộp...",
    noAdminApps: "Không có đơn nào trong danh mục này",
    adminNoteLabel: "Ghi chú Admin (bắt buộc nếu từ chối)",
    adminNotePlaceholder: "Nhập ghi chú...",
    rejectBtn: "Từ chối",
    approveBtn: "Phê duyệt",
    processing: "Đang xử lý...",
    submittedOn2: "Nộp",
    rejectReason: "Lý do từ chối",

    // 404
    notFoundTitle: "Trang không tồn tại",
    notFoundDesc: "Trang bạn đang tìm không tồn tại hoặc đã bị xóa.\nHãy quay về trang chủ để tiếp tục.",
    toHome: "Về trang chủ",
    goBack: "Quay lại",

    // CV Builder
    cvBuilderTitle: "Trình dựng CV",
    cvBuilderDesc: "Chọn các dòng hồ sơ và tạo CV của bạn",
    exportCV: "Xuất CV",
    profileBank: "Kho dòng hồ sơ",
    selectTemplate: "Chọn mẫu CV",
    previewCV: "Xem trước CV",
    noProfileItems: "Chưa có dòng hồ sơ nào",
    addFromProfile: "Thêm từ Hồ sơ",
    exportDialogTitle: "Xuất CV",
    fileName: "Tên file",
    exportNote: "CV sẽ được lưu vào Tủ hồ sơ/CV của bạn.",
    exportPDF: "Xuất PDF",
    exportSuccess: "Xuất CV thành công!",
    redirectingCV: "Đang chuyển đến Tủ hồ sơ...",
    templateModern: "Hiện đại",
    templateClassic: "Cổ điển",
    templateMinimal: "Tối giản",
    cvSectionLanguage: "Ngôn ngữ tiêu đề CV",
    customSectionTitles: "Tùy chỉnh tiêu đề mục",
    resetTitles: "Mặc định",
    sectionTitlesHint: "Tùy chỉnh tên các tiêu đề hiển thị trong CV theo ý bạn",
    masterPool: "Kho dòng hồ sơ Master (Database)",
    addAllSource: "+ Thêm tất cả",
    allSourceAdded: "Tất cả dòng hồ sơ master đã có trong CV. Bạn có thể bấm tạo dòng mới hoặc tải file CV để nhập thêm.",
    createNewLine: "Tạo dòng mới",
    uploadIngest: "Tải CV bóc tách",
    uploadingIngestText: "Đang bóc tách...",
    sortAndSelect: "Sắp xếp & chọn dòng",
    selectAll: "Chọn tất cả",
    deselectAll: "Bỏ chọn",
    noSelectedLines: "Chưa có dòng nào. Thêm từ kho ở trên hoặc tạo dòng mới.",
    cvPreviewTitle: "Bản xem trước CV",
    exitBtn: "Thoát",
    linesSummary: (selected: number, newCount: number, edited: number) =>
      `${selected} dòng hiển thị • ${newCount} dòng mới • ${edited} dòng đã sửa`,
    editLineTitle: "Chỉnh sửa dòng",
    newBadge: "Dòng mới",
    categoryLabel: "Phân loại",
    contentLabel: "Nội dung",
    nameLabel: "Họ và tên",
    emailLabel: "Email",
    phoneLabel: "Số điện thoại",
    collapse: "Thu gọn",
    expand: "Mở rộng",
    selectedTemplateText: "Mẫu đang chọn:",
    applySampleTemplate: "Áp dụng nội dung mẫu",
    applySampleTemplateHint: "Tải các dòng thông tin mẫu chuẩn để bạn điền và chỉnh sửa nhanh chóng",
    sampleApplied: "Đã nạp nội dung mẫu CV!",
    saveToProfile: "Lưu vào hồ sơ gốc",
    savingToProfile: "Đang lưu...",
    savedToProfileSuccess: "Đã lưu các dòng CV vào hồ sơ cá nhân!",
    extractedLinesSuccess: (n: number) => `Đã bóc tách thành công ${n} dòng thông tin từ CV!`,
    editCVContent: "Chỉnh sửa CV",
    duplicateCV: "Sao chép & Sửa",
    duplicateSuccess: "Đã tạo bản sao CV!",
    renameCV: "Đổi tên",
    deleteCV: "Xóa CV",
    deleteCVConfirmTitle: "Xác nhận xóa CV",
    deleteCVConfirmDesc: "Bạn có chắc chắn muốn xóa CV này? CV sẽ bị xóa khỏi Tủ hồ sơ và không còn được dùng cho các đề xuất tìm việc.",
    deleteCVSuccess: "Đã xóa CV thành công!",
    deleteCVFailed: "Xóa CV thất bại",
    deleteChatSession: "Xóa cuộc trò chuyện",
    deleteChatConfirmTitle: "Xác nhận xóa cuộc trò chuyện",
    deleteChatConfirmDesc: "Bạn có chắc chắn muốn xóa cuộc trò chuyện này? Lịch sử tin nhắn sẽ bị xóa vĩnh viễn.",
    clearAllChat: "Xóa tất cả",
    clearAllChatConfirmTitle: "Xác nhận xóa toàn bộ lịch sử",
    clearAllChatConfirmDesc: "Bạn có chắc chắn muốn xóa toàn bộ lịch sử các cuộc trò chuyện đã lưu? Hành động này không thể hoàn tác.",
    deleteChatSuccess: "Đã xóa cuộc trò chuyện!",
    clearAllChatSuccess: "Đã xóa toàn bộ lịch sử trò chuyện!",
    deleteChatFailed: "Không thể xóa cuộc trò chuyện",
  },


  en: {
    // Navbar
    home: "Home",
    jobs: "Jobs",
    login: "Login",
    register: "Sign Up",
    aiSuggestions: "Job Suggestions",
    profile: "Profile",
    cvVault: "CV Vault",
    applications: "My Applications",
    recruiterRegister: "Become a Recruiter",
    aiCandidates: "Candidate Suggestions",
    dashboard: "Recruitment Board",
    adminMenu: "Admin Menu",
    logout: "Sign Out",

    // HomePage
    heroTag: "Vietnam's #1 Smart Recruitment Platform",
    heroTitle1: "Find your dream",
    heroTitle2: "job today",
    heroDesc: "Connect talented candidates with top employers. AI-powered job matching tailored to your profile.",
    startFree: "Get Started Free",
    toDashboard: "Go to Dashboard",
    toAdminMenu: "Admin Menu",
    findJobNow: "Find Jobs Now",
    searchJobs: "Search Jobs",
    searchPlaceholder: "Search position, company, skills...",
    search: "Search",
    statJobs: "Job Listings",
    statCandidates: "Registered Candidates",
    statCompanies: "Partner Companies",
    statSuccess: "Hiring Success Rate",
    latestJobs: "Latest Jobs",
    latestJobsDesc: "Open opportunities from top companies",
    viewAll: "View all",
    forYou: "Built for You",
    forYouDesc: "NextJob serves everyone with purpose-built tools",
    forCandidate: "For Candidates",
    forCandidateDesc: "Build a professional profile, upload your CV, and get AI-powered job suggestions. Track your applications in real time.",
    viewMyProfile: "View Profile",
    forRecruiter: "For Recruiters",
    forRecruiterDesc: "Post jobs, review applicants, and get AI-matched candidate suggestions. Manage your entire hiring pipeline.",
    registerRecruiter: "Register as Recruiter",
    forAdmin: "For Admins",
    forAdminDesc: "Approve recruiter applications, manage accounts, and monitor platform activity.",
    accessAdmin: "Access Admin Panel",
    ctaTitle: "Ready to get started?",
    ctaDesc: "Join thousands of candidates and recruiters already using NextJob",
    registerFree: "Sign Up Free",
    footerDesc: "Smart Recruitment Platform.",

    // Job card / list
    viewDetail: "View Detail",
    save: "Save",
    unsave: "Unsave",
    active: "Hiring",
    expired: "Expired",
    deadline: "Deadline",
    postedOn: "Posted",
    salary: "Negotiable",
    noResult: "No results found",
    noResultDesc: "Try adjusting your keywords or filters",
    clearFilters: "Clear Filters",
    filterType: "Job Type",
    filterLocation: "Location",
    allLocations: "All locations",
    savedOnly: "Saved",
    jobCount: (active: number, total: number) => `${active} open / ${total} total listings`,

    // Common
    loading: "Loading...",
    cancel: "Cancel",
    save_btn: "Save",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    back: "Back",
    submit: "Submit",
    close: "Close",

    // Auth
    welcomeBack: "Welcome back",
    loginDesc: "Sign in to continue your job search",
    demoAccounts: "Demo accounts (password: password123)",
    email: "Email",
    password: "Password",
    loggingIn: "Signing in...",
    loginBtn: "Sign In",
    noAccount: "Don't have an account?",
    registerNow: "Sign up now",
    createAccount: "Create Account",
    registerDesc: "Sign up free and start your journey",
    fullName: "Full Name",
    minPassword: "Minimum 8 characters",
    registering: "Creating account...",
    registerBtn: "Sign Up",
    hasAccount: "Already have an account?",
    loginLink: "Sign In",
    registerSuccess: "Registration successful!",
    redirectingProfile: "Redirecting to profile...",
    pwWeak: "Weak", pwMedium: "Fair", pwStrong: "Strong",
    loginError: "Incorrect email or password. Please try again.",
    registerError: "This email is already registered. Please use a different email.",

    // Profile
    profileTitle: "Profile",
    personalInfo: "Personal Information",
    phone: "Phone",
    avatarUrl: "Avatar URL",
    avatarTitle: "Profile Picture",
    uploadAvatar: "Upload Photo",
    changeAvatar: "Change Photo",
    removeAvatar: "Remove Photo",
    avatarHint: "Supports JPG, PNG, WEBP — max 2MB",
    avatarUploadSuccess: "Avatar updated successfully!",
    avatarRemoveSuccess: "Avatar removed successfully!",
    uploadingAvatar: "Uploading photo...",
    savingProfile: "Saving...",
    saveInfo: "Save Changes",
    saved: "Saved!",
    profileItems: "Profile Entries",
    addItem: "Add Entry",
    noItems: "No profile entries yet. Add information to make CV creation easier!",
    itemType: "Type",
    itemTitle: "Title",
    itemContent: "Content",
    deleteItemTitle: "Delete Entry",
    deleteItemMsg: "Are you sure you want to delete this profile entry?",
    editItemTitle: "Edit Profile Entry",
    editItem: "Edit Entry",
    saveChanges: "Save Changes",
    savingChanges: "Saving...",
    updatedItemSuccess: "Entry updated successfully!",
    userManagement: "User Management (Admin)",

    // CV Vault
    cvVaultTitle: "CV Vault",
    cvCount: (n: number) => `${n} CV${n !== 1 ? "s" : ""} stored`,
    buildCV: "Build CV",
    createCV: "Create CV",
    uploadCV: "Upload",
    uploadHint: "Supports PDF, DOC, DOCX — max 10MB",
    cvName: "Name your CV...",
    noCV: "No CVs yet",
    noCVDesc: "Upload or auto-generate a CV from your profile",
    uploadBtn: "Upload",
    uploadSuccess: "Uploaded successfully!",
    setDefault: "Set as Default",
    openFile: "Open File",
    defaultBadge: "Default",
    appsUsing: (n: number) => `${n} application${n !== 1 ? "s" : ""}`,
    unused: "Not used",
    deleteCVTitle: "Delete CV",
    deleteCVMsg: "Are you sure you want to delete this CV? This action cannot be undone.",
    deleteCVBtn: "Delete CV",

    // Applications
    myApplications: "My Applications",
    noApps: "No applications yet",
    noAppsDesc: "Find jobs and apply to track them here",
    findJobs: "Find Jobs",
    submittedOn: "Submitted",
    progress: "Application Timeline",
    withdrawApp: "Withdraw",
    withdrawTitle: "Withdraw Application",
    withdrawMsg: "Are you sure you want to withdraw this application? This cannot be undone.",
    withdrawBtn: "Withdraw",

    // Job detail
    backToJobs: "Jobs",
    applyNow: "Apply Now",
    selectCV: "Select CV",
    coverLetter: "Cover Letter",
    coverLetterOpt: "(optional)",
    coverLetterPlaceholder: "Introduce yourself and explain why you're a great fit...",
    submitting: "Submitting...",
    applyBtn: "Apply",
    applySuccess: "Application submitted!",
    applySuccessDesc: "The recruiter will contact you soon.",
    myAppsLink: "View my applications",
    alreadyApplied: "Already Applied",
    appliedOn: "Applied on",
    appliedCV: "CV",
    toMyApps: "Go to My Applications",
    noCV_apply: "You don't have a CV yet. Upload one to apply.",
    toCVVault: "Go to CV Vault",
    expiredJob: "Application Closed",
    expiredDesc: "This job listing has expired.",
    loginToApply: "Sign in to apply for this position",
    jobDesc: "Job Description",
    requirements: "Requirements",
    benefits: "Benefits",
    aboutCompany: "About",
    similarJobs: "Similar Jobs",
    location: "Location",
    salaryLabel: "Salary",
    deadlineLabel: "Deadline",

    // AI Suggestions
    aiJobTitle: "AI Job Suggestions",
    aiJobDesc: "Personalized to your profile",
    aiWelcome: "Hello! I'm NextJob's AI assistant 👋\nI can help you find the best jobs matched to your profile. Ask me anything or tap a suggestion chip below!",
    chipSuggest: "Suggest matching jobs",
    chipRemote: "High-paying remote jobs",
    chipHanoi: "Jobs in Hanoi",
    chatPlaceholder: "Message AI...",
    viewJob: "View Job",
    match: (n: number) => `${n}% match`,

    // Recruiter register
    recruiterTitle: "Become a Recruiter",
    recruiterDesc: "Fill in your company details to be approved by Admin",
    companyName: "Company Name",
    companyNameReq: "Company name is required.",
    companyEmail: "Company Email",
    website: "Company Website",
    licenseUrl: "Business License URL",
    sendApp: "Submit Application",
    sending: "Submitting...",
    sentSuccess: "Application submitted!",
    sentSuccessDesc: "Admin will review and respond within 1-2 business days.",
    backHome: "Back to Home",
    alreadyRecruiter: "You are already a Recruiter",
    alreadyRecruiterDesc: "Access the Recruitment Board to manage your job posts and applicants.",
    toDashboard2: "Go to Dashboard",
    pendingApp: "Your application is under review",
    rejectNote: "Rejection reason",
    adminNote: "Admin note",

    // Dashboard
    dashboardTitle: "Recruitment Board",
    jobListTitle: "Job Listings",
    createJob: "Post Job",
    noJobs: "No jobs yet",
    jobTitle: "Job Title",
    jobDesc2: "Job Description",
    creating: "Creating...",
    createBtn: "Post",
    selectJobHint: "Select a job listing to view applicants",
    noApplicants: "No applicants yet",
    update: "Update",
    newStatus: "New Status",
    noteLabel: "Note",
    notePlaceholder: "Note (optional)",

    // AI Candidates
    aiCandTitle: "AI Candidate Suggestions",
    aiCandDesc: "Find the best candidates for your position",
    selectJob: "-- Select a job listing --",
    chipCandSuggest: "Suggest matching candidates",
    chipRankScore: "Rank by match score",
    candPlaceholder: "Message AI...",
    selectJobFirst: "Select a job listing first",
    viewCV: "View CV",
    noCV_job: "No CVs submitted for this position.",

    // Admin
    adminTitle: "Recruiter Applications",
    adminDesc: "Review and approve recruiter registration requests",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    searchAdmin: "Search by company, email, applicant...",
    noAdminApps: "No applications in this category",
    adminNoteLabel: "Admin note (required when rejecting)",
    adminNotePlaceholder: "Enter note...",
    rejectBtn: "Reject",
    approveBtn: "Approve",
    processing: "Processing...",
    submittedOn2: "Submitted",
    rejectReason: "Rejection reason",

    // 404
    notFoundTitle: "Page Not Found",
    notFoundDesc: "The page you're looking for doesn't exist or has been removed.\nReturn to the homepage to continue.",
    toHome: "Back to Home",
    goBack: "Go Back",

    // CV Builder
    cvBuilderTitle: "CV Builder",
    cvBuilderDesc: "Select profile entries and build your CV",
    exportCV: "Export CV",
    profileBank: "Profile Entry Bank",
    selectTemplate: "Choose Template",
    previewCV: "CV Preview",
    noProfileItems: "No profile entries yet",
    addFromProfile: "Add from Profile",
    exportDialogTitle: "Export CV",
    fileName: "File Name",
    exportNote: "CV will be saved to your CV Vault.",
    exportPDF: "Export as PDF",
    exportSuccess: "CV exported successfully!",
    redirectingCV: "Redirecting to CV Vault...",
    templateModern: "Modern",
    templateClassic: "Classic",
    templateMinimal: "Minimal",
    cvSectionLanguage: "CV Section Language",
    customSectionTitles: "Customize Section Titles",
    resetTitles: "Reset",
    sectionTitlesHint: "Customize the headings displayed in your CV as you prefer",
    masterPool: "Master Profile Pool (Database)",
    addAllSource: "+ Add all",
    allSourceAdded: "All master profile entries are in the CV. You can create a new entry or import from a CV file.",
    createNewLine: "New entry",
    uploadIngest: "Import from CV",
    uploadingIngestText: "Importing...",
    sortAndSelect: "Sort & Select entries",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    noSelectedLines: "No entries added yet. Add from the pool above or create a new entry.",
    cvPreviewTitle: "CV Preview",
    exitBtn: "Exit",
    linesSummary: (selected: number, newCount: number, edited: number) =>
      `${selected} visible • ${newCount} new • ${edited} edited`,
    editLineTitle: "Edit entry",
    newBadge: "New",
    categoryLabel: "Category",
    contentLabel: "Content",
    nameLabel: "Full Name",
    emailLabel: "Email",
    phoneLabel: "Phone Number",
    collapse: "Collapse",
    expand: "Expand",
    selectedTemplateText: "Selected template:",
    applySampleTemplate: "Use Starter Template",
    applySampleTemplateHint: "Load realistic sample entries ready for quick editing",
    sampleApplied: "Starter template content loaded!",
    saveToProfile: "Save to Master Profile",
    savingToProfile: "Saving...",
    savedToProfileSuccess: "Saved CV entries to your master profile!",
    extractedLinesSuccess: (n: number) => `Successfully extracted ${n} entries from CV!`,
    editCVContent: "Edit CV",
    duplicateCV: "Duplicate & Edit",
    duplicateSuccess: "CV duplicated successfully!",
    renameCV: "Rename",
    deleteCV: "Delete CV",
    deleteCVConfirmTitle: "Confirm Delete CV",
    deleteCVConfirmDesc: "Are you sure you want to delete this CV? It will be removed from your CV Vault and will no longer be used for job recommendations.",
    deleteCVSuccess: "CV deleted successfully!",
    deleteCVFailed: "Failed to delete CV",
    deleteChatSession: "Delete conversation",
    deleteChatConfirmTitle: "Confirm Delete Conversation",
    deleteChatConfirmDesc: "Are you sure you want to delete this conversation? Message history will be permanently deleted.",
    clearAllChat: "Clear all",
    clearAllChatConfirmTitle: "Confirm Clear All History",
    clearAllChatConfirmDesc: "Are you sure you want to delete all saved conversations? This action cannot be undone.",
    deleteChatSuccess: "Conversation deleted successfully!",
    clearAllChatSuccess: "All chat history cleared successfully!",
    deleteChatFailed: "Failed to delete conversation",
  },


};

type Translations = typeof translations.vi;

interface LangContextType {
  lang: Lang;
  t: Translations;
  toggleLang: () => void;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("vi");
  const toggleLang = () => setLang((l) => (l === "vi" ? "en" : "vi"));
  return (
    <LangContext.Provider value={{ lang, t: translations[lang] as Translations, toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be inside LangProvider");
  return ctx;
}
