import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "vi" | "en";

const translations = {
  vi: {
    // Navbar
    home: "Trang chủ",
    jobs: "Việc làm",
    login: "Đăng nhập",
    register: "Đăng ký",
    aiSuggestions: "Gợi ý việc",
    profile: "Hồ sơ",
    cvVault: "Tủ hồ sơ/CV",
    applications: "Đơn ứng tuyển",
    recruiterRegister: "Đăng ký Recruiter",
    aiCandidates: "Gợi ý ứng viên",
    repoEvaluation: "Đánh giá Repo",
    aiInterview: "Phỏng vấn AI",
    dashboard: "Bàn tuyển dụng",
    adminMenu: "Menu Admin",
    logout: "Đăng xuất",
    toggleTheme: "Đổi giao diện",
    account: "Tài khoản",

    // HomePage
    heroTag: "Nền tảng tuyển dụng thông minh #1 Việt Nam",
    heroTitle1: "Tìm việc làm",
    heroTitle2: "mơ ước của bạn",
    heroDesc: "Kết nối ứng viên tài năng với nhà tuyển dụng uy tín. AI thông minh gợi ý công việc phù hợp nhất với hồ sơ của bạn.",
    startFree: "Bắt đầu miễn phí",
    toDashboard: "Đến Bàn tuyển dụng",
    toAdminMenu: "Menu Admin",
    findJobNow: "Tìm việc ngay",
    searchJobs: "Tìm kiếm việc làm",
    searchPlaceholder: "Tìm kiếm vị trí, công ty, kỹ năng...",
    search: "Tìm kiếm",
    statJobs: "Tin tuyển dụng",
    statCandidates: "Ứng viên đăng ký",
    statCompanies: "Công ty đối tác",
    statSuccess: "Tỷ lệ tuyển thành công",
    latestJobs: "Việc làm mới nhất",
    latestJobsDesc: "Cơ hội tuyển dụng đang mở từ các công ty hàng đầu",
    viewAll: "Xem tất cả",
    forYou: "Dành riêng cho bạn",
    forYouDesc: "NextJob phục vụ mọi đối tượng với những công cụ được thiết kế đặc biệt",
    forCandidate: "Dành cho Ứng viên",
    forCandidateDesc: "Tạo hồ sơ chuyên nghiệp, tải CV và nhận gợi ý việc làm phù hợp từ AI. Theo dõi trạng thái đơn ứng tuyển realtime.",
    viewMyProfile: "Xem hồ sơ",
    forRecruiter: "Dành cho Nhà tuyển dụng",
    forRecruiterDesc: "Đăng tin tuyển dụng, duyệt đơn ứng viên và nhận gợi ý ứng viên phù hợp từ AI. Quản lý toàn bộ quy trình tuyển dụng.",
    registerRecruiter: "Đăng ký Recruiter",
    forAdmin: "Dành cho Quản trị viên",
    forAdminDesc: "Phê duyệt đơn đăng ký nhà tuyển dụng, quản lý tài khoản và giám sát hoạt động toàn hệ thống.",
    accessAdmin: "Truy cập Admin",
    ctaTitle: "Sẵn sàng bắt đầu?",
    ctaDesc: "Tham gia cùng hàng nghìn ứng viên và nhà tuyển dụng đang sử dụng NextJob",
    registerFree: "Đăng ký miễn phí",
    footerDesc: "Nền tảng tuyển dụng thông minh.",

    // Job card / list
    jobListTitle: "Việc làm",
    jobListDesc: "tin đang tuyển",
    jobSearchPlaceholder: "Tiêu đề, công ty, địa điểm, mô tả...",
    filterBtn: "Lọc",
    clearAllFilters: "Xóa tất cả bộ lọc",
    viewDetail: "Xem chi tiết",
    save: "Lưu",
    unsave: "Bỏ lưu",
    active: "Đang tuyển",
    expired: "Hết hạn",
    deadline: "Hạn nộp",
    postedOn: "Đăng ngày",
    salary: "Thỏa thuận",
    nationwide: "Toàn quốc",
    companyDefault: "Công ty",
    noResult: "Không tìm thấy kết quả",
    noResultDesc: "Thử điều chỉnh từ khóa hoặc bộ lọc của bạn",
    clearFilters: "Xóa bộ lọc",
    filterType: "Loại hình",
    filterLocation: "Địa điểm",
    allLocations: "Tất cả địa điểm",
    savedOnly: "Đã lưu",
    compareBtn: "So sánh",
    compareSelected: "Đã chọn",
    compareLetter: (label: string) => `So sánh (${label})`,
    addCompareTooltip: "Thêm vào so sánh việc làm",
    removeCompareTooltip: "Bỏ chọn so sánh",
    saveJobTooltip: "Lưu việc làm",
    unsaveJobTooltip: "Bỏ lưu việc làm",
    jobCount: (active: number, total: number) => `${active} tin đang tuyển / ${total} tổng tin`,
    maxCompareWarning: "Chỉ có thể so sánh tối đa 5 việc làm cùng lúc",
    loginToCompare: "Vui lòng đăng nhập để sử dụng tính năng so sánh việc làm với CV",
    selectAtLeast2ToCompare: "Vui lòng chọn từ 2 đến 5 việc làm để so sánh",
    unsavedJobSuccess: "Đã bỏ lưu việc làm",
    savedJobSuccess: "Đã lưu việc làm thành công!",
    loadJobsError: "Không tải được danh sách việc làm.",

    // Common
    loading: "Đang tải...",
    cancel: "Hủy",
    save_btn: "Lưu",
    confirm: "Xác nhận",
    delete: "Xóa",
    edit: "Sửa",
    add: "Thêm",
    back: "Quay lại",
    submit: "Nộp",
    close: "Đóng",
    exit: "Thoát",
    actions: "Thao tác",
    status: "Trạng thái",
    or: "hoặc",
    reset: "Đặt lại",

    // Auth
    welcomeBack: "Chào mừng trở lại",
    loginDesc: "Đăng nhập để tiếp tục hành trình tìm việc",
    demoAccounts: "Tài khoản demo (mật khẩu: password123)",
    email: "Email",
    password: "Mật khẩu",
    loggingIn: "Đang đăng nhập...",
    loginBtn: "Đăng nhập",
    loginWithGoogle: "Đăng nhập với Google",
    registerWithGoogle: "Đăng ký với Google",
    redirectingGoogle: "Đang chuyển đến Google...",
    noAccount: "Chưa có tài khoản?",
    registerNow: "Đăng ký ngay",
    createAccount: "Tạo tài khoản",
    registerDesc: "Đăng ký miễn phí, bắt đầu hành trình của bạn",
    fullName: "Họ và tên",
    fullNamePlaceholder: "Nguyễn Văn A",
    emailPlaceholder: "ten@email.com",
    passwordPlaceholder: "••••••••",
    minPassword: "Tối thiểu 8 ký tự",
    registering: "Đang đăng ký...",
    registerBtn: "Đăng ký",
    hasAccount: "Đã có tài khoản?",
    loginLink: "Đăng nhập",
    registerSuccess: "Đăng ký thành công!",
    redirectingProfile: "Đang chuyển đến trang hồ sơ...",
    checkEmailTitle: "Kiểm tra email",
    checkEmailDesc: "Một liên kết xác minh đã được gửi đến email của bạn.",
    checkEmailResetDesc: (em: string) => `Nếu ${em} tồn tại trong hệ thống, chúng tôi đã gửi một liên kết để đặt lại mật khẩu.`,
    pwWeak: "Yếu",
    pwMedium: "Trung bình",
    pwStrong: "Mạnh",
    loginError: "Email hoặc mật khẩu không đúng. Vui lòng thử lại.",
    registerError: "Email này đã được đăng ký. Vui lòng dùng email khác.",
    supabaseConfigError: "Hệ thống Supabase chưa được cấu hình.",
    pwMinLengthError: "Mật khẩu phải có ít nhất 8 ký tự.",
    pwMismatchError: "Mật khẩu xác nhận không khớp.",
    forgotPassword: "Quên mật khẩu?",
    forgotPasswordDesc: "Nhập email để nhận liên kết đặt lại mật khẩu",
    sendResetLink: "Gửi liên kết đặt lại",
    sendingResetLink: "Đang gửi...",
    backToLogin: "Quay lại đăng nhập",
    resetPasswordTitle: "Đặt mật khẩu mới",
    resetPasswordDesc: "Nhập mật khẩu mới cho tài khoản của bạn",
    newPasswordLabel: "Mật khẩu mới",
    confirmPasswordLabel: "Xác nhận mật khẩu",
    confirmPasswordPlaceholder: "Nhập lại mật khẩu mới",
    resetPasswordBtn: "Đặt lại mật khẩu",
    resetPasswordSuccess: "Đổi mật khẩu thành công!",
    invalidResetLinkTitle: "Liên kết không hợp lệ hoặc đã hết hạn",
    invalidResetLinkDesc: "Vui lòng yêu cầu gửi lại liên kết đặt lại mật khẩu.",
    requestNewLink: "Yêu cầu liên kết mới",
    verifyingLink: "Đang xác minh liên kết...",

    // Profile
    profileTitle: "Hồ sơ",
    personalInfo: "Thông tin cá nhân",
    phone: "Điện thoại",
    avatarUrl: "URL ảnh đại diện",
    avatarTitle: "Ảnh đại diện",
    uploadAvatar: "Tải ảnh lên",
    changeAvatar: "Đổi ảnh",
    removeAvatar: "Gỡ ảnh",
    takePhoto: "Chụp ảnh",
    avatarHint: "Hỗ trợ JPG, PNG, WEBP — tối đa 5MB",
    avatarUploadSuccess: "Đã cập nhật ảnh đại diện!",
    avatarRemoveSuccess: "Đã gỡ ảnh đại diện!",
    avatarUploadError: "Không thể tải ảnh lên",
    avatarTooLarge: "Ảnh vượt quá dung lượng tối đa 5MB.",
    avatarInvalidType: "Chỉ chấp nhận file ảnh JPG, PNG, WEBP hoặc GIF.",
    uploadingAvatar: "Đang tải ảnh lên...",
    savingProfile: "Đang lưu...",
    saveInfo: "Lưu thông tin",
    saved: "Đã lưu!",
    profileItems: "Dòng hồ sơ",
    addItem: "Thêm dòng",
    noItems: "Chưa có dòng hồ sơ nào. Thêm thông tin để tạo CV dễ dàng hơn!",
    itemType: "Loại",
    itemTitle: "Tiêu đề",
    itemContent: "Nội dung",
    deleteItemTitle: "Xóa dòng hồ sơ",
    deleteItemMsg: "Bạn có chắc muốn xóa dòng hồ sơ này không?",
    editItemTitle: "Chỉnh sửa dòng hồ sơ",
    editItem: "Sửa dòng",
    saveChanges: "Lưu thay đổi",
    savingChanges: "Đang lưu...",
    updatedItemSuccess: "Đã cập nhật dòng hồ sơ!",
    userManagement: "Quản lý người dùng (Admin)",
    missingContent: "Thiếu nội dung",
    pleaseEnterContent: "Vui lòng nhập nội dung dòng hồ sơ!",
    addedEntrySuccess: "Đã thêm dòng hồ sơ!",
    deletedEntrySuccess: "Đã xóa dòng hồ sơ!",
    roleChangedSuccess: "Đã đổi vai trò người dùng!",

    // CV Vault
    cvVaultTitle: "Tủ hồ sơ/CV",
    cvCount: (n: number) => `${n} CV đang lưu`,
    buildCV: "Tạo CV",
    createCV: "Tạo CV",
    uploadCV: "Tải lên",
    uploadHint: "Hỗ trợ PDF, DOC, DOCX — tối đa 10MB",
    cvName: "Đặt tên cho CV...",
    noCV: "Chưa có CV nào",
    noCVDesc: "Tải lên hoặc tạo CV tự động từ hồ sơ",
    uploadBtn: "Tải lên",
    uploadSuccess: "Tải lên thành công!",
    setDefault: "Đặt làm mặc định",
    openFile: "Mở file",
    defaultBadge: "Mặc định",
    appsUsing: (n: number) => `${n} đơn ứng tuyển`,
    unused: "Chưa dùng",
    deleteCVTitle: "Xóa CV",
    deleteCVMsg: "Bạn có chắc muốn xóa CV này? Hành động này không thể hoàn tác.",
    deleteCVBtn: "Xóa CV",
    publicSharing: "Chia sẻ công khai",
    makePublic: "Mở công khai",
    makePrivate: "Tắt công khai",
    renameCV: "Đổi tên",
    duplicateCV: "Sao chép & Sửa",
    duplicateSuccess: "Đã tạo bản sao CV!",
    deleteCVSuccess: "Đã xóa CV thành công!",
    deleteCVFailed: "Xóa CV thất bại",
    deleteCVConfirmTitle: "Xác nhận xóa CV",
    deleteCVConfirmDesc: "Bạn có chắc chắn muốn xóa CV này? CV sẽ bị xóa khỏi Tủ hồ sơ và không còn được dùng cho các đề xuất tìm việc.",

    // Applications
    myApplications: "Đơn ứng tuyển của tôi",
    noApps: "Chưa có đơn ứng tuyển nào",
    noAppsDesc: "Tìm việc và nộp đơn để theo dõi tại đây",
    findJobs: "Tìm việc làm",
    submittedOn: "Nộp",
    progress: "Tiến trình đơn",
    withdrawApp: "Rút đơn",
    withdrawTitle: "Rút đơn ứng tuyển",
    withdrawMsg: "Bạn có chắc chắn muốn rút đơn ứng tuyển này? Hành động này không thể hoàn tác.",
    withdrawBtn: "Rút đơn",
    withdrawnSuccess: "Đã rút đơn ứng tuyển!",
    loadAppsError: "Không tải được danh sách đơn",
    candidateWithdrewNote: "Ứng viên rút đơn",

    // Job detail
    backToJobs: "Việc làm",
    applyNow: "Ứng tuyển ngay",
    selectCV: "Chọn CV",
    selectCVPlaceholder: "-- Chọn CV từ Tủ hồ sơ --",
    coverLetter: "Thư giới thiệu",
    coverLetterOpt: "(tùy chọn)",
    coverLetterPlaceholder: "Giới thiệu bản thân và lý do bạn phù hợp với vị trí này...",
    submitting: "Đang nộp...",
    applyBtn: "Nộp đơn",
    applySuccess: "Nộp đơn thành công!",
    applySuccessDesc: "Nhà tuyển dụng sẽ liên hệ bạn sớm.",
    myAppsLink: "Xem đơn của tôi",
    alreadyApplied: "Đã nộp đơn",
    appliedOn: "Ngày nộp",
    appliedCV: "CV đã nộp",
    toMyApps: "Đến Đơn của tôi",
    noCV_apply: "Bạn chưa có CV. Tải CV lên để ứng tuyển.",
    toCVVault: "Đến Tủ hồ sơ/CV",
    expiredJob: "Hết hạn nộp đơn",
    expiredDesc: "Tin tuyển dụng này đã hết hạn hoặc không còn nhận hồ sơ.",
    loginToApply: "Đăng nhập để ứng tuyển vị trí này",
    jobDesc: "Mô tả công việc",
    requirements: "Yêu cầu công việc",
    benefits: "Quyền lợi & Phúc lợi",
    aboutCompany: "Về công ty",
    similarJobs: "Việc tương tự",
    location: "Địa điểm",
    salaryLabel: "Mức lương",
    deadlineLabel: "Hạn nộp",
    jobNotFound: "Không tìm thấy tin tuyển dụng.",

    // AI Suggestions
    aiJobTitle: "Gợi ý việc làm AI",
    aiJobDesc: "Được cá nhân hóa theo hồ sơ của bạn",
    aiWelcome: "Xin chào! Tôi là trợ lý AI của NextJob 👋\nTôi có thể giúp bạn tìm những công việc phù hợp nhất dựa trên hồ sơ của bạn. Hãy hỏi tôi hoặc nhấn chip gợi ý bên dưới!",
    chipSuggest: "Gợi ý việc phù hợp",
    chipRemote: "Việc remote lương cao",
    chipHanoi: "Việc tại Hà Nội",
    chatPlaceholder: "Nhắn tin với AI...",
    viewJob: "Xem tin",
    match: (n: number) => `${n}% phù hợp`,
    highMatch: "Phù hợp cao",
    normalMatch: "Bình thường",
    lowMatch: "Chưa phù hợp",
    matchReason: "Lý do gợi ý",
    filterConfig: "Bộ lọc & Ngưỡng",
    minFitScore: "Ngưỡng điểm phù hợp tối thiểu",
    maxJobsCount: "Số lượng tin tối đa",
    skillWeight: "Trọng số kỹ năng",
    chatHistory: "Lịch sử trò chuyện",
    newChatSession: "Cuộc trò chuyện mới",
    clearAllChatHistory: "Xóa toàn bộ lịch sử",
    deleteChatSession: "Xóa cuộc trò chuyện",
    deleteChatConfirmTitle: "Xác nhận xóa cuộc trò chuyện",
    deleteChatConfirmDesc: "Bạn có chắc chắn muốn xóa cuộc trò chuyện này? Lịch sử tin nhắn sẽ bị xóa vĩnh viễn.",
    clearAllChat: "Xóa tất cả",
    clearAllChatConfirmTitle: "Xác nhận xóa toàn bộ lịch sử",
    clearAllChatConfirmDesc: "Bạn có chắc chắn muốn xóa toàn bộ lịch sử các cuộc trò chuyện đã lưu? Hành động này không thể hoàn tác.",
    deleteChatSuccess: "Đã xóa cuộc trò chuyện!",
    clearAllChatSuccess: "Đã xóa toàn bộ lịch sử trò chuyện!",
    deleteChatFailed: "Không thể xóa cuộc trò chuyện",

    // Recruiter register
    recruiterTitle: "Đăng ký Nhà tuyển dụng",
    recruiterDesc: "Điền thông tin công ty để được phê duyệt bởi Admin",
    companyName: "Tên công ty",
    companyNameReq: "Tên công ty là bắt buộc.",
    companyEmail: "Email công ty",
    website: "Website công ty",
    licenseUrl: "Đường dẫn giấy phép kinh doanh",
    sendApp: "Gửi đơn đăng ký",
    updateApp: "Cập nhật đơn",
    sending: "Đang gửi...",
    sentSuccess: "Đã gửi đơn đăng ký thành công!",
    updateSuccess: "Đã cập nhật đơn đăng ký!",
    sentSuccessDesc: "Admin sẽ xem xét và phản hồi trong vòng 1-2 ngày làm việc.",
    backHome: "Về trang chủ",
    alreadyRecruiter: "Bạn đã là Nhà tuyển dụng",
    alreadyRecruiterDesc: "Truy cập Bàn tuyển dụng để quản lý tin đăng và đơn ứng viên.",
    toDashboard2: "Đến Bàn tuyển dụng",
    pendingApp: "Đơn đăng ký đang chờ xét duyệt",
    latestAppStatus: (st: string) => `Đơn gần nhất: ${st}`,
    rejectNote: "Lý do từ chối",
    adminNote: "Ghi chú từ Admin",

    // Dashboard
    dashboardTitle: "Bàn tuyển dụng",
    jobListHeading: "Danh sách tin tuyển dụng",
    createJob: "Tạo tin mới",
    editJob: "Chỉnh sửa tin tuyển dụng",
    noJobs: "Chưa có tin nào",
    noJobsDesc: "Hãy tạo tin tuyển dụng đầu tiên của bạn để bắt đầu tiếp cận ứng viên.",
    jobTitle: "Tiêu đề công việc",
    jobDesc2: "Mô tả công việc",
    jobReqs: "Yêu cầu ứng viên",
    jobBenefits: "Quyền lợi được hưởng",
    jobLocation: "Địa điểm làm việc",
    jobEmpType: "Loại hình công việc",
    jobSalaryMin: "Lương tối thiểu",
    jobSalaryMax: "Lương tối đa",
    jobCurrency: "Đơn vị tiền tệ",
    jobDeadline: "Hạn nhận hồ sơ",
    jobStatusLabel: "Trạng thái tin",
    creating: "Đang tạo...",
    updating: "Đang cập nhật...",
    createBtn: "Tạo tin",
    selectJobHint: "Chọn một tin tuyển dụng ở danh sách bên trái để xem đơn ứng viên",
    noApplicants: "Chưa có ứng viên nào nộp đơn",
    noApplicantsDesc: "Các đơn ứng tuyển cho vị trí này sẽ xuất hiện tại đây.",
    update: "Cập nhật",
    newStatus: "Trạng thái mới",
    noteLabel: "Ghi chú tiến trình",
    notePlaceholder: "Ghi chú nội bộ (tùy chọn)",
    applicantListTitle: "Danh sách ứng viên",
    viewResume: "Xem CV",
    compareCandidatesBtn: "So sánh ứng viên",
    companySelectLabel: "Công ty",
    mustSelectCompany: "Vui lòng chọn công ty",
    jobCreatedSuccess: "Tạo tin tuyển dụng thành công!",
    jobUpdatedSuccess: "Cập nhật tin tuyển dụng thành công!",
    stageUpdatedSuccess: "Đã cập nhật trạng thái đơn ứng tuyển!",

    // AI Candidates
    aiCandTitle: "Gợi ý ứng viên AI",
    aiCandDesc: "Tìm ứng viên phù hợp nhất cho vị trí của bạn",
    selectJob: "-- Chọn tin tuyển dụng --",
    chipCandSuggest: "Gợi ý ứng viên phù hợp",
    chipRankScore: "Xếp hạng theo điểm",
    candPlaceholder: "Nhắn tin với AI...",
    selectJobFirst: "Vui lòng chọn tin tuyển dụng trước",
    viewCV: "Xem CV",
    noCV_job: "Chưa có CV nộp cho vị trí này.",
    verifiedSkillsBadge: "Kỹ năng đã xác thực",
    publicJobSeekerBadge: "Ứng viên tìm việc",
    filterCandidates: "Bộ lọc ứng viên",
    includePublicSeekers: "Bao gồm ứng viên tự do",
    verifiedOnlyLabel: "Chỉ ứng viên có Repo/Kỹ năng đã xác thực",
    maxCandidatesCount: "Số ứng viên tối đa",

    // AI Interview
    aiInterviewTitle: "Trợ lý Phỏng vấn AI",
    aiInterviewDesc: "Tạo bộ câu hỏi phỏng vấn chuẩn hóa, rubric và follow-up cá nhân hóa theo từng ứng viên và JD",
    selectCandidate: "-- Chọn ứng viên --",
    selectJobInterview: "-- Chọn tin tuyển dụng --",
    generateQuestions: "Tạo bộ câu hỏi",
    generatingQuestions: "AI đang phân tích và tạo câu hỏi...",
    questionCount: "Số lượng câu hỏi",
    coverageThreshold: "Ngưỡng bao phủ yêu cầu JD (%)",
    regenerate: "Tạo lại",
    approveInterview: "Duyệt bộ câu hỏi",
    approvedBadge: "Đã duyệt",
    reviewerNotes: "Ghi chú của người phỏng vấn",
    copyQuestion: "Sao chép câu hỏi",
    copied: "Đã sao chép!",
    expectedAnswer: "Dàn ý câu trả lời kỳ vọng",
    rubricEvaluation: "Thang điểm đánh giá (Rubric)",
    rubricExcellent: "Xuất sắc (9-10)",
    rubricAcceptable: "Đạt yêu cầu (6-8)",
    rubricPoor: "Chưa đạt (1-5)",
    followUpQuestions: "Câu hỏi đào sâu mở rộng (Follow-up)",
    mappedJD: "Đối chiếu yêu cầu JD",
    testedSkills: "Kỹ năng kiểm tra",
    projectRef: "Tham chiếu dự án",
    difficulty: "Độ khó",
    catTechnical: "Kỹ thuật chuyên sâu",
    catSystemDesign: "Thiết kế hệ thống",
    catBehavioral: "Hành vi & Tình huống",
    catProjectDeepDive: "Khai thác Dự án",
    catProblemSolving: "Giải quyết vấn đề",
    catCodeReview: "Review & Tối ưu Code",
    catCultureFit: "Văn hóa & Đội ngũ",
    diffEasy: "Dễ",
    diffMedium: "Trung bình",
    diffHard: "Khó",

    // Repo Evaluation
    repoEvalTitle: "Đánh giá Repository GitHub AI",
    repoEvalDesc: "Phân tích chất lượng mã nguồn, độ phức tạp, kiểm thử, CI/CD và năng lực thực tế từ GitHub của ứng viên",
    candidateTab: "Ứng viên đánh giá Repo",
    recruiterTab: "Nhà tuyển dụng đánh giá",
    batchEvalTab: "Đánh giá hàng loạt",
    evalHistoryTab: "Lịch sử đánh giá",
    inputRepoUrl: "Nhập đường dẫn GitHub Repository",
    repoUrlPlaceholder: "https://github.com/username/repository",
    extractFromCV: "Bóc tách Repo từ CV",
    evaluateBtn: "Bắt đầu đánh giá",
    evaluatingText: "AI đang phân tích kiến trúc mã nguồn...",
    overallScore: "Điểm tổng thể",
    dimCompleteness: "Độ hoàn thiện & Tính năng",
    dimComplexity: "Độ phức tạp & Kiến trúc",
    dimOptimization: "Tối ưu hóa & Hiệu năng",
    dimCodeCleanliness: "Độ sạch & Tiêu chuẩn mã",
    dimProjectUnderstanding: "Tư duy & Thấu hiểu dự án",
    heuristicsTitle: "Chỉ số thống kê mã nguồn",
    fileCountLabel: "Tổng số tệp",
    testRatioLabel: "Tỷ lệ kiểm thử",
    docRatioLabel: "Tài liệu hóa",
    languagesLabel: "Ngôn ngữ sử dụng",
    ciCdLabel: "CI/CD Tích hợp",
    dockerLabel: "Container/Docker",
    aiSummaryTitle: "Nhận xét tổng quan của AI",
    redFlagsTitle: "Lưu ý & Điểm cần cải thiện",
    strengthsTitle: "Điểm nổi bật",
    recommendationsTitle: "Khuyến nghị phỏng vấn",

    // Admin
    adminTitle: "Trang Quản trị Admin",
    adminDesc: "Phê duyệt đơn đăng ký Nhà tuyển dụng và Quản lý sửa quyền người dùng",
    adminRequestsTab: "Duyệt đăng ký Recruiter",
    adminRolesTab: "Quản lý & Sửa quyền",
    pending: "Chờ duyệt",
    approved: "Đã phê duyệt",
    rejected: "Đã từ chối",
    searchAdmin: "Tìm theo công ty, email...",
    searchAdminUsers: "Tìm theo tên, email, vai trò...",
    noAdminApps: "Không có đơn nào trong mục này",
    noAdminUsers: "Không tìm thấy tài khoản phù hợp.",
    userListHeading: "Danh sách tài khoản người dùng",
    adminNoteLabel: "Ghi chú Admin (bắt buộc nếu từ chối)",
    adminNotePlaceholder: "Ghi chú Admin...",
    rejectBtn: "Từ chối",
    approveBtn: "Phê duyệt",
    processing: "Đang xử lý...",
    submittedOn2: "Nộp",
    rejectReason: "Lý do từ chối",
    currentRole: "Quyền hiện tại:",
    updateRoleSuccess: "Cập nhật phân quyền người dùng thành công!",

    // 404
    notFoundTitle: "Trang không tồn tại",
    notFoundDesc: "Trang bạn đang tìm không tồn tại hoặc đã bị xóa.\nHãy quay về trang chủ để tiếp tục.",
    toHome: "Về trang chủ",
    goBack: "Quay lại",

    // CV Builder
    cvBuilderTitle: "Trình dựng CV",
    cvBuilderDesc: "Chọn các dòng hồ sơ và tạo CV của bạn",
    exportCV: "Xuất CV",
    profileBank: "Kho dòng hồ sơ",
    selectTemplate: "Chọn mẫu CV",
    previewCV: "Xem trước CV",
    noProfileItems: "Chưa có dòng hồ sơ nào",
    addFromProfile: "Thêm từ Hồ sơ",
    exportDialogTitle: "Xuất CV",
    fileName: "Tên file",
    exportNote: "CV sẽ được lưu vào Tủ hồ sơ/CV của bạn.",
    exportPDF: "Xuất PDF",
    exportSuccess: "Xuất CV thành công!",
    redirectingCV: "Đang chuyển đến Tủ hồ sơ...",
    templateModern: "Hiện đại",
    templateClassic: "Cổ điển",
    templateMinimal: "Tối giản",
    cvSectionLanguage: "Ngôn ngữ tiêu đề CV",
    customSectionTitles: "Tùy chỉnh tiêu đề mục",
    resetTitles: "Mặc định",
    sectionTitlesHint: "Tùy chỉnh tên các tiêu đề hiển thị trong CV theo ý bạn",
    masterPool: "Kho dòng hồ sơ Master (Database)",
    addAllSource: "+ Thêm tất cả",
    allSourceAdded: "Tất cả dòng hồ sơ master đã có trong CV. Bạn có thể bấm tạo dòng mới hoặc tải file CV để nhập thêm.",
    createNewLine: "Tạo dòng mới",
    uploadIngest: "Tải CV bóc tách",
    uploadingIngestText: "Đang bóc tách...",
    sortAndSelect: "Sắp xếp & chọn dòng",
    selectAll: "Chọn tất cả",
    deselectAll: "Bỏ chọn",
    noSelectedLines: "Chưa có dòng nào. Thêm từ kho ở trên hoặc tạo dòng mới.",
    cvPreviewTitle: "Bản xem trước CV",
    exitBtn: "Thoát",
    linesSummary: (selected: number, newCount: number, edited: number) =>
      `${selected} dòng hiển thị • ${newCount} dòng mới • ${edited} dòng đã sửa`,
    editLineTitle: "Chỉnh sửa dòng",
    newBadge: "Dòng mới",
    categoryLabel: "Phân loại",
    contentLabel: "Nội dung",
    nameLabel: "Họ và tên",
    emailLabel: "Email",
    phoneLabel: "Số điện thoại",
    collapse: "Thu gọn",
    expand: "Mở rộng",
    selectedTemplateText: "Mẫu đang chọn:",
    applySampleTemplate: "Áp dụng nội dung mẫu",
    applySampleTemplateHint: "Tải các dòng thông tin mẫu chuẩn để bạn điền và chỉnh sửa nhanh chóng",
    sampleApplied: "Đã nạp nội dung mẫu CV!",
    saveToProfile: "Lưu vào hồ sơ gốc",
    savingToProfile: "Đang lưu...",
    savedToProfileSuccess: "Đã lưu các dòng CV vào hồ sơ cá nhân!",
    extractedLinesSuccess: (n: number) => `Đã bóc tách thành công ${n} dòng thông tin từ CV!`,
    editCVContent: "Chỉnh sửa CV",

    // Comparison Modals & Docks
    jobCompareDockTitle: "Đã chọn:",
    compareJobsModalTitle: "So sánh trực quan Việc làm với CV",
    compareCandidatesModalTitle: "So sánh trực quan Ứng viên",
    tabCharts: "Biểu đồ so sánh",
    tabMatrix: "Bảng ma trận chi tiết",
    tabDeepDive: "Phân tích chuyên sâu",
    tabWinner: "AI Khuyến nghị",
    radarChartTitle: "Biểu đồ Radar Năng lực",
    barChartTitle: "Điểm số theo từng khía cạnh",
    metricExperience: "Kinh nghiệm làm việc",
    metricHardSkills: "Kỹ năng chuyên môn",
    metricEducation: "Học vấn & Bằng cấp",
    metricProject: "Dự án thực tế",
    metricSoftSkills: "Kỹ năng mềm & Phù hợp",
    clearAll: "Xóa tất cả",
    startCompare: "Bắt đầu so sánh",
    comparing: "Đang phân tích so sánh...",
    publicCVTitle: "Chia sẻ CV công khai",
    publicCVDesc: "Tạo liên kết xem trực tiếp và mã QR để chia sẻ CV cho nhà tuyển dụng",
    copyLink: "Sao chép liên kết",
    linkCopied: "Đã sao chép liên kết!",
    scanQRCode: "Quét mã QR để xem trên điện thoại",
  },

  en: {
    // Navbar
    home: "Home",
    jobs: "Jobs",
    login: "Login",
    register: "Sign Up",
    aiSuggestions: "Job Suggestions",
    profile: "Profile",
    cvVault: "CV Vault",
    applications: "My Applications",
    recruiterRegister: "Register as Recruiter",
    aiCandidates: "AI Candidate Match",
    repoEvaluation: "Repo Evaluation",
    aiInterview: "AI Interview",
    dashboard: "Recruiter Dashboard",
    adminMenu: "Admin Menu",
    logout: "Sign out",
    toggleTheme: "Toggle theme",
    account: "Account",

    // HomePage
    heroTag: "Vietnam's #1 Smart Recruitment Platform",
    heroTitle1: "Find your dream",
    heroTitle2: "job today",
    heroDesc: "Connect talented candidates with top employers. AI-powered job matching tailored to your profile.",
    startFree: "Get Started Free",
    toDashboard: "Go to Dashboard",
    toAdminMenu: "Admin Menu",
    findJobNow: "Find Jobs Now",
    searchJobs: "Search Jobs",
    searchPlaceholder: "Search position, company, skills...",
    search: "Search",
    statJobs: "Job Listings",
    statCandidates: "Registered Candidates",
    statCompanies: "Partner Companies",
    statSuccess: "Hiring Success Rate",
    latestJobs: "Latest Jobs",
    latestJobsDesc: "Open opportunities from top companies",
    viewAll: "View all",
    forYou: "Built for You",
    forYouDesc: "NextJob serves everyone with purpose-built tools",
    forCandidate: "For Candidates",
    forCandidateDesc: "Build a professional profile, upload your CV, and get AI-powered job suggestions. Track your applications in real time.",
    viewMyProfile: "View Profile",
    forRecruiter: "For Recruiters",
    forRecruiterDesc: "Post jobs, review applicants, and get AI-matched candidate suggestions. Manage your entire hiring pipeline.",
    registerRecruiter: "Register as Recruiter",
    forAdmin: "For Admins",
    forAdminDesc: "Approve recruiter applications, manage accounts, and monitor platform activity.",
    accessAdmin: "Access Admin Panel",
    ctaTitle: "Ready to get started?",
    ctaDesc: "Join thousands of candidates and recruiters already using NextJob",
    registerFree: "Sign Up Free",
    footerDesc: "Smart Recruitment Platform.",

    // Job card / list
    jobListTitle: "Jobs",
    jobListDesc: "open listings",
    jobSearchPlaceholder: "Title, company, location, description...",
    filterBtn: "Filters",
    clearAllFilters: "Clear all filters",
    viewDetail: "View Detail",
    save: "Save",
    unsave: "Unsave",
    active: "Hiring",
    expired: "Expired",
    deadline: "Deadline",
    postedOn: "Posted",
    salary: "Negotiable",
    nationwide: "Nationwide",
    companyDefault: "Company",
    noResult: "No results found",
    noResultDesc: "Try adjusting your keywords or filters",
    clearFilters: "Clear Filters",
    filterType: "Job Type",
    filterLocation: "Location",
    allLocations: "All locations",
    savedOnly: "Saved",
    compareBtn: "Compare",
    compareSelected: "Selected",
    compareLetter: (label: string) => `Compare (${label})`,
    addCompareTooltip: "Add to job comparison",
    removeCompareTooltip: "Remove from comparison",
    saveJobTooltip: "Save job",
    unsaveJobTooltip: "Unsave job",
    jobCount: (active: number, total: number) => `${active} open / ${total} total listings`,
    maxCompareWarning: "You can only compare up to 5 jobs at a time",
    loginToCompare: "Please sign in to use the job comparison feature",
    selectAtLeast2ToCompare: "Please select 2 to 5 jobs to compare",
    unsavedJobSuccess: "Job unsaved",
    savedJobSuccess: "Job saved successfully!",
    loadJobsError: "Failed to load job listings.",

    // Common
    loading: "Loading...",
    cancel: "Cancel",
    save_btn: "Save",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    back: "Back",
    submit: "Submit",
    close: "Close",
    exit: "Exit",
    actions: "Actions",
    status: "Status",
    or: "or",
    reset: "Reset",

    // Auth
    welcomeBack: "Welcome back",
    loginDesc: "Sign in to continue your job search",
    demoAccounts: "Demo accounts (password: password123)",
    email: "Email",
    password: "Password",
    loggingIn: "Signing in...",
    loginBtn: "Sign In",
    loginWithGoogle: "Sign in with Google",
    registerWithGoogle: "Sign up with Google",
    redirectingGoogle: "Redirecting to Google...",
    noAccount: "Don't have an account?",
    registerNow: "Sign up now",
    createAccount: "Create Account",
    registerDesc: "Sign up free and start your journey",
    fullName: "Full Name",
    fullNamePlaceholder: "John Doe",
    emailPlaceholder: "name@email.com",
    passwordPlaceholder: "••••••••",
    minPassword: "Minimum 8 characters",
    registering: "Creating account...",
    registerBtn: "Sign Up",
    hasAccount: "Already have an account?",
    loginLink: "Sign In",
    registerSuccess: "Registration successful!",
    redirectingProfile: "Redirecting to profile...",
    checkEmailTitle: "Check your email",
    checkEmailDesc: "A verification link has been sent to your email address.",
    checkEmailResetDesc: (em: string) => `If ${em} exists in our system, we've sent a password reset link.`,
    pwWeak: "Weak",
    pwMedium: "Fair",
    pwStrong: "Strong",
    loginError: "Incorrect email or password. Please try again.",
    registerError: "This email is already registered. Please use a different email.",
    supabaseConfigError: "Supabase system is not properly configured.",
    pwMinLengthError: "Password must be at least 8 characters.",
    pwMismatchError: "Password confirmation does not match.",
    forgotPassword: "Forgot password?",
    forgotPasswordDesc: "Enter your email to receive a password reset link",
    sendResetLink: "Send Reset Link",
    sendingResetLink: "Sending...",
    backToLogin: "Back to sign in",
    resetPasswordTitle: "Reset Password",
    resetPasswordDesc: "Enter a new password for your account",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your new password",
    resetPasswordBtn: "Reset Password",
    resetPasswordSuccess: "Password changed successfully!",
    invalidResetLinkTitle: "Invalid or Expired Link",
    invalidResetLinkDesc: "Please request a new password reset link.",
    requestNewLink: "Request new link",
    verifyingLink: "Verifying link...",

    // Profile
    profileTitle: "Profile",
    personalInfo: "Personal Information",
    phone: "Phone",
    avatarUrl: "Avatar URL",
    avatarTitle: "Profile Picture",
    uploadAvatar: "Upload Photo",
    changeAvatar: "Change Photo",
    removeAvatar: "Remove Photo",
    takePhoto: "Take Photo",
    avatarHint: "Supports JPG, PNG, WEBP — max 5MB",
    avatarUploadSuccess: "Avatar updated successfully!",
    avatarRemoveSuccess: "Avatar removed successfully!",
    avatarUploadError: "Failed to upload photo",
    avatarTooLarge: "Image exceeds the 5MB size limit.",
    avatarInvalidType: "Only JPG, PNG, WEBP or GIF image files are allowed.",
    uploadingAvatar: "Uploading photo...",
    savingProfile: "Saving...",
    saveInfo: "Save Changes",
    saved: "Saved!",
    profileItems: "Profile Entries",
    addItem: "Add Entry",
    noItems: "No profile entries yet. Add information to make CV creation easier!",
    itemType: "Type",
    itemTitle: "Title",
    itemContent: "Content",
    deleteItemTitle: "Delete Entry",
    deleteItemMsg: "Are you sure you want to delete this profile entry?",
    editItemTitle: "Edit Profile Entry",
    editItem: "Edit Entry",
    saveChanges: "Save Changes",
    savingChanges: "Saving...",
    updatedItemSuccess: "Entry updated successfully!",
    userManagement: "User Management (Admin)",
    missingContent: "Missing content",
    pleaseEnterContent: "Please enter entry content!",
    addedEntrySuccess: "Added profile entry!",
    deletedEntrySuccess: "Entry deleted!",
    roleChangedSuccess: "User role changed successfully!",

    // CV Vault
    cvVaultTitle: "CV Vault",
    cvCount: (n: number) => `${n} CV${n !== 1 ? "s" : ""} stored`,
    buildCV: "Build CV",
    createCV: "Create CV",
    uploadCV: "Upload",
    uploadHint: "Supports PDF, DOC, DOCX — max 10MB",
    cvName: "Name your CV...",
    noCV: "No CVs yet",
    noCVDesc: "Upload or auto-generate a CV from your profile",
    uploadBtn: "Upload",
    uploadSuccess: "Uploaded successfully!",
    setDefault: "Set as Default",
    openFile: "Open File",
    defaultBadge: "Default",
    appsUsing: (n: number) => `${n} application${n !== 1 ? "s" : ""}`,
    unused: "Not used",
    deleteCVTitle: "Delete CV",
    deleteCVMsg: "Are you sure you want to delete this CV? This action cannot be undone.",
    deleteCVBtn: "Delete CV",
    publicSharing: "Public Sharing",
    makePublic: "Make Public",
    makePrivate: "Make Private",
    renameCV: "Rename",
    duplicateCV: "Duplicate & Edit",
    duplicateSuccess: "CV duplicated successfully!",
    deleteCVSuccess: "CV deleted successfully!",
    deleteCVFailed: "Failed to delete CV",
    deleteCVConfirmTitle: "Confirm Delete CV",
    deleteCVConfirmDesc: "Are you sure you want to delete this CV? It will be removed from your CV Vault and will no longer be used for job recommendations.",

    // Applications
    myApplications: "My Applications",
    noApps: "No applications yet",
    noAppsDesc: "Find jobs and apply to track them here",
    findJobs: "Find Jobs",
    submittedOn: "Submitted",
    progress: "Application Timeline",
    withdrawApp: "Withdraw",
    withdrawTitle: "Withdraw Application",
    withdrawMsg: "Are you sure you want to withdraw this application? This cannot be undone.",
    withdrawBtn: "Withdraw",
    withdrawnSuccess: "Application withdrawn successfully!",
    loadAppsError: "Failed to load application list",
    candidateWithdrewNote: "Candidate withdrew application",

    // Job detail
    backToJobs: "Jobs",
    applyNow: "Apply Now",
    selectCV: "Select CV",
    selectCVPlaceholder: "-- Select a CV from Vault --",
    coverLetter: "Cover Letter",
    coverLetterOpt: "(optional)",
    coverLetterPlaceholder: "Introduce yourself and explain why you're a great fit...",
    submitting: "Submitting...",
    applyBtn: "Apply",
    applySuccess: "Application submitted!",
    applySuccessDesc: "The recruiter will contact you soon.",
    myAppsLink: "View my applications",
    alreadyApplied: "Already Applied",
    appliedOn: "Applied on",
    appliedCV: "Submitted CV",
    toMyApps: "Go to My Applications",
    noCV_apply: "You don't have a CV yet. Upload one to apply.",
    toCVVault: "Go to CV Vault",
    expiredJob: "Application Closed",
    expiredDesc: "This job listing has expired or is no longer accepting applications.",
    loginToApply: "Sign in to apply for this position",
    jobDesc: "Job Description",
    requirements: "Requirements",
    benefits: "Benefits",
    aboutCompany: "About",
    similarJobs: "Similar Jobs",
    location: "Location",
    salaryLabel: "Salary",
    deadlineLabel: "Deadline",
    jobNotFound: "Job listing not found.",

    // AI Suggestions
    aiJobTitle: "AI Job Suggestions",
    aiJobDesc: "Personalized to your profile",
    aiWelcome: "Hello! I'm NextJob's AI assistant 👋\nI can help you find the best jobs matched to your profile. Ask me anything or tap a suggestion chip below!",
    chipSuggest: "Suggest matching jobs",
    chipRemote: "High-paying remote jobs",
    chipHanoi: "Jobs in Hanoi",
    chatPlaceholder: "Message AI...",
    viewJob: "View Job",
    match: (n: number) => `${n}% match`,
    highMatch: "Strong Match",
    normalMatch: "Fair Match",
    lowMatch: "Low Match",
    matchReason: "Match Reason",
    filterConfig: "Filters & Thresholds",
    minFitScore: "Minimum match score threshold",
    maxJobsCount: "Maximum jobs count",
    skillWeight: "Skill match weight",
    chatHistory: "Chat History",
    newChatSession: "New Conversation",
    clearAllChatHistory: "Clear All History",
    deleteChatSession: "Delete conversation",
    deleteChatConfirmTitle: "Confirm Delete Conversation",
    deleteChatConfirmDesc: "Are you sure you want to delete this conversation? Message history will be permanently deleted.",
    clearAllChat: "Clear all",
    clearAllChatConfirmTitle: "Confirm Clear All History",
    clearAllChatConfirmDesc: "Are you sure you want to delete all saved conversations? This action cannot be undone.",
    deleteChatSuccess: "Conversation deleted successfully!",
    clearAllChatSuccess: "All chat history cleared successfully!",
    deleteChatFailed: "Failed to delete conversation",

    // Recruiter register
    recruiterTitle: "Become a Recruiter",
    recruiterDesc: "Fill in your company details to be approved by Admin",
    companyName: "Company Name",
    companyNameReq: "Company name is required.",
    companyEmail: "Company Email",
    website: "Company Website",
    licenseUrl: "Business License URL",
    sendApp: "Submit Application",
    updateApp: "Update Application",
    sending: "Submitting...",
    sentSuccess: "Application submitted successfully!",
    updateSuccess: "Application updated successfully!",
    sentSuccessDesc: "Admin will review and respond within 1-2 business days.",
    backHome: "Back to Home",
    alreadyRecruiter: "You are already a Recruiter",
    alreadyRecruiterDesc: "Access the Recruitment Board to manage your job posts and applicants.",
    toDashboard2: "Go to Dashboard",
    pendingApp: "Your application is under review",
    latestAppStatus: (st: string) => `Latest status: ${st}`,
    rejectNote: "Rejection reason",
    adminNote: "Admin note",

    // Dashboard
    dashboardTitle: "Recruitment Board",
    jobListHeading: "Job Listings",
    createJob: "Post New Job",
    editJob: "Edit Job Listing",
    noJobs: "No jobs yet",
    noJobsDesc: "Create your first job listing to start reaching candidates.",
    jobTitle: "Job Title",
    jobDesc2: "Job Description",
    jobReqs: "Candidate Requirements",
    jobBenefits: "Benefits & Perks",
    jobLocation: "Work Location",
    jobEmpType: "Employment Type",
    jobSalaryMin: "Minimum Salary",
    jobSalaryMax: "Maximum Salary",
    jobCurrency: "Currency",
    jobDeadline: "Application Deadline",
    jobStatusLabel: "Job Status",
    creating: "Creating...",
    updating: "Updating...",
    createBtn: "Post Job",
    selectJobHint: "Select a job listing on the left to view applicants",
    noApplicants: "No applicants yet",
    noApplicantsDesc: "Applications submitted for this job will appear here.",
    update: "Update",
    newStatus: "New Status",
    noteLabel: "Pipeline Note",
    notePlaceholder: "Internal note (optional)",
    applicantListTitle: "Applicant List",
    viewResume: "View CV",
    compareCandidatesBtn: "Compare Candidates",
    companySelectLabel: "Company",
    mustSelectCompany: "Please select a company",
    jobCreatedSuccess: "Job listing created successfully!",
    jobUpdatedSuccess: "Job listing updated successfully!",
    stageUpdatedSuccess: "Application status updated successfully!",

    // AI Candidates
    aiCandTitle: "AI Candidate Suggestions",
    aiCandDesc: "Find the best candidates for your position",
    selectJob: "-- Select a job listing --",
    chipCandSuggest: "Suggest matching candidates",
    chipRankScore: "Rank by match score",
    candPlaceholder: "Message AI...",
    selectJobFirst: "Please select a job listing first",
    viewCV: "View CV",
    noCV_job: "No CVs submitted for this position.",
    verifiedSkillsBadge: "Verified Skills",
    publicJobSeekerBadge: "Job Seeker",
    filterCandidates: "Candidate Filters",
    includePublicSeekers: "Include active job seekers",
    verifiedOnlyLabel: "Verified Repo/Skills only",
    maxCandidatesCount: "Maximum candidates count",

    // AI Interview
    aiInterviewTitle: "AI Interview Assistant",
    aiInterviewDesc: "Generate standardized interview questions, scoring rubrics, and follow-ups tailored to each candidate and JD",
    selectCandidate: "-- Select Candidate --",
    selectJobInterview: "-- Select Job Listing --",
    generateQuestions: "Generate Questions",
    generatingQuestions: "AI is analyzing profile & generating questions...",
    questionCount: "Number of Questions",
    coverageThreshold: "JD Requirements Coverage Threshold (%)",
    regenerate: "Regenerate",
    approveInterview: "Approve Question Set",
    approvedBadge: "Approved",
    reviewerNotes: "Interviewer Notes",
    copyQuestion: "Copy Question",
    copied: "Copied!",
    expectedAnswer: "Expected Answer Outline",
    rubricEvaluation: "Scoring Rubric",
    rubricExcellent: "Excellent (9-10)",
    rubricAcceptable: "Acceptable (6-8)",
    rubricPoor: "Needs Improvement (1-5)",
    followUpQuestions: "Follow-up Exploration Questions",
    mappedJD: "Mapped JD Requirement",
    testedSkills: "Skills Tested",
    projectRef: "Project Reference",
    difficulty: "Difficulty",
    catTechnical: "Technical In-depth",
    catSystemDesign: "System Design",
    catBehavioral: "Behavioral & Situational",
    catProjectDeepDive: "Project Deep Dive",
    catProblemSolving: "Problem Solving",
    catCodeReview: "Code Review & Optimization",
    catCultureFit: "Culture & Team Fit",
    diffEasy: "Easy",
    diffMedium: "Medium",
    diffHard: "Hard",

    // Repo Evaluation
    repoEvalTitle: "AI GitHub Repository Evaluation",
    repoEvalDesc: "Analyze source code quality, complexity, testing, CI/CD, and practical skills directly from candidate repositories",
    candidateTab: "Candidate Repo Eval",
    recruiterTab: "Recruiter Applicant Eval",
    batchEvalTab: "Batch Evaluation",
    evalHistoryTab: "Evaluation History",
    inputRepoUrl: "Enter GitHub Repository URL",
    repoUrlPlaceholder: "https://github.com/username/repository",
    extractFromCV: "Extract Repos from CV",
    evaluateBtn: "Start Evaluation",
    evaluatingText: "AI is analyzing code architecture...",
    overallScore: "Overall Score",
    dimCompleteness: "Completeness & Features",
    dimComplexity: "Complexity & Architecture",
    dimOptimization: "Optimization & Performance",
    dimCodeCleanliness: "Code Cleanliness & Standards",
    dimProjectUnderstanding: "Domain Understanding & Design",
    heuristicsTitle: "Codebase Heuristic Metrics",
    fileCountLabel: "Total Files",
    testRatioLabel: "Test Ratio",
    docRatioLabel: "Documentation",
    languagesLabel: "Languages Used",
    ciCdLabel: "CI/CD Pipeline",
    dockerLabel: "Container/Docker",
    aiSummaryTitle: "AI Summary Assessment",
    redFlagsTitle: "Key Warnings & Potential Issues",
    strengthsTitle: "Key Strengths",
    recommendationsTitle: "Interview Recommendations",

    // Admin
    adminTitle: "Admin Management Portal",
    adminDesc: "Review recruiter applications and manage user roles & permissions",
    adminRequestsTab: "Review Recruiter Requests",
    adminRolesTab: "Roles & Permissions",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    searchAdmin: "Search by company, email...",
    searchAdminUsers: "Search by name, email, role...",
    noAdminApps: "No applications in this category",
    noAdminUsers: "No matching accounts found.",
    userListHeading: "User Account Directory",
    adminNoteLabel: "Admin note (required when rejecting)",
    adminNotePlaceholder: "Admin note...",
    rejectBtn: "Reject",
    approveBtn: "Approve",
    processing: "Processing...",
    submittedOn2: "Submitted",
    rejectReason: "Rejection reason",
    currentRole: "Current role:",
    updateRoleSuccess: "User role updated successfully!",

    // 404
    notFoundTitle: "Page Not Found",
    notFoundDesc: "The page you're looking for doesn't exist or has been removed.\nReturn to the homepage to continue.",
    toHome: "Back to Home",
    goBack: "Go Back",

    // CV Builder
    cvBuilderTitle: "CV Builder",
    cvBuilderDesc: "Select profile entries and build your CV",
    exportCV: "Export CV",
    profileBank: "Profile Entry Bank",
    selectTemplate: "Choose Template",
    previewCV: "CV Preview",
    noProfileItems: "No profile entries yet",
    addFromProfile: "Add from Profile",
    exportDialogTitle: "Export CV",
    fileName: "File Name",
    exportNote: "CV will be saved to your CV Vault.",
    exportPDF: "Export as PDF",
    exportSuccess: "CV exported successfully!",
    redirectingCV: "Redirecting to CV Vault...",
    templateModern: "Modern",
    templateClassic: "Classic",
    templateMinimal: "Minimal",
    cvSectionLanguage: "CV Section Language",
    customSectionTitles: "Customize Section Titles",
    resetTitles: "Reset",
    sectionTitlesHint: "Customize the headings displayed in your CV as you prefer",
    masterPool: "Master Profile Pool (Database)",
    addAllSource: "+ Add all",
    allSourceAdded: "All master profile entries are in the CV. You can create a new entry or import from a CV file.",
    createNewLine: "New entry",
    uploadIngest: "Import from CV",
    uploadingIngestText: "Importing...",
    sortAndSelect: "Sort & Select entries",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    noSelectedLines: "No entries added yet. Add from the pool above or create a new entry.",
    cvPreviewTitle: "CV Preview",
    exitBtn: "Exit",
    linesSummary: (selected: number, newCount: number, edited: number) =>
      `${selected} visible • ${newCount} new • ${edited} edited`,
    editLineTitle: "Edit entry",
    newBadge: "New",
    categoryLabel: "Category",
    contentLabel: "Content",
    nameLabel: "Full Name",
    emailLabel: "Email",
    phoneLabel: "Phone Number",
    collapse: "Collapse",
    expand: "Expand",
    selectedTemplateText: "Selected template:",
    applySampleTemplate: "Use Starter Template",
    applySampleTemplateHint: "Load realistic sample entries ready for quick editing",
    sampleApplied: "Starter template content loaded!",
    saveToProfile: "Save to Master Profile",
    savingToProfile: "Saving...",
    savedToProfileSuccess: "Saved CV entries to your master profile!",
    extractedLinesSuccess: (n: number) => `Successfully extracted ${n} entries from CV!`,
    editCVContent: "Edit CV",

    // Comparison Modals & Docks
    jobCompareDockTitle: "Selected:",
    compareJobsModalTitle: "Visual Job vs CV Comparison",
    compareCandidatesModalTitle: "Visual Candidate Comparison",
    tabCharts: "Visual Charts",
    tabMatrix: "Detailed Matrix",
    tabDeepDive: "Dimension Deep Dive",
    tabWinner: "AI Winner Recommendation",
    radarChartTitle: "Skills Radar Breakdown",
    barChartTitle: "Dimension Score Breakdown",
    metricExperience: "Work Experience",
    metricHardSkills: "Technical Skills",
    metricEducation: "Education & Degree",
    metricProject: "Practical Projects",
    metricSoftSkills: "Soft Skills & Fit",
    clearAll: "Clear All",
    startCompare: "Compare Now",
    comparing: "Analyzing comparison...",
    publicCVTitle: "Public CV Sharing",
    publicCVDesc: "Generate a direct link and QR code to share your CV with employers",
    copyLink: "Copy Link",
    linkCopied: "Link copied to clipboard!",
    scanQRCode: "Scan QR code to view on mobile",
  },
};

type Translations = typeof translations.vi;

interface LangContextType {
  lang: Lang;
  t: Translations;
  toggleLang: () => void;
  setLanguage: (lang: Lang) => void;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    try {
      const saved = localStorage.getItem("app_lang") as Lang | null;
      if (saved === "vi" || saved === "en") return saved;
    } catch {
      // ignore
    }
    return "vi";
  });

  const toggleLang = () => {
    setLang((prev) => {
      const next = prev === "vi" ? "en" : "vi";
      try {
        localStorage.setItem("app_lang", next);
      } catch {
        // ignore
      }
      return next;
    });
  };

  const setLanguage = (newLang: Lang) => {
    try {
      localStorage.setItem("app_lang", newLang);
    } catch {
      // ignore
    }
    setLang(newLang);
  };

  return (
    <LangContext.Provider
      value={{
        lang,
        t: translations[lang] as Translations,
        toggleLang,
        setLanguage,
      }}
    >
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be inside LangProvider");
  return ctx;
}

