"""Append real VietJobs IT job postings into supabase/seed.sql.

Filters data_find/data/vietjobs/VietJobs_full.csv down to ~90 real Vietnamese
IT job descriptions spread across the 15 groups in
data_find/data/it-job-categories.md (the same groups used by
data_find/generated_cv/metadata.csv), then writes a `do $$ ... $$;` block —
its own pool of IT companies + job_posts rows, owned by the recruiter account
seed.sql already creates — into supabase/seed.sql, between the
VIETJOBS-IT-SEED markers. Runs automatically with `supabase db reset` since
it's now part of seed.sql, no separate apply step needed.

Re-running this script replaces only the marked block, leaving the rest of
seed.sql untouched.

    python scripts/build_vietjobs_it_seed.py
"""

from __future__ import annotations

import csv
import re
import uuid
from ast import literal_eval
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "data_find" / "data" / "vietjobs" / "VietJobs_full.csv"
SEED_PATH = ROOT / "supabase" / "seed.sql"

BEGIN_MARKER = "-- === BEGIN VIETJOBS-IT-SEED (generated by scripts/build_vietjobs_it_seed.py) ==="
END_MARKER = "-- === END VIETJOBS-IT-SEED ==="

RECRUITER_ID = "22222222-2222-2222-2222-222222222222"
NAMESPACE = uuid.UUID("8f2e6a4c-1b7d-4e2a-9c3f-5d6b0a7e1c22")

# ---------------------------------------------------------------------------
# Group definitions: (group_name, include keywords, exclude keywords, quota)
# ---------------------------------------------------------------------------
GROUPS = [
    (1, "Software Development", [
        "frontend", "front-end", "backend", "back-end", "full-stack", "fullstack",
        "full stack", "mobile developer", "ios developer", "android developer",
        "game developer", "desktop application", "web developer",
        "flutter developer", "react developer", "node developer", "java developer",
        ".net developer", "php developer", "lập trình viên", "software developer",
        "software engineer", "unity developer", "developer",
    ], [], 1),
    (2, "DevOps/Infrastructure", [
        "devops", "site reliability", "sre", "release engineer", "platform engineer",
    ], [], 1),
    (3, "System Administration", [
        "network administrator", "server administrator", "it support", "helpdesk",
        "help desk", "it operations", "system administrator", "quản trị hệ thống",
        "quản trị mạng", "nhân viên it", "it staff", "kỹ thuật mạng máy tính",
    ], ["devops", "developer"], 1),
    (4, "Cybersecurity", [
        "security analyst", "penetration tester", "security engineer", "soc analyst",
        "incident response", "malware analyst", "grc", "an toàn thông tin",
        "bảo mật", "pentest", "redteam", "red team",
    ], [], 1),
    (5, "Data", [
        "data analyst", "data engineer", "data scientist", "database administrator",
        " dba ", "bi developer", "business intelligence", "phân tích dữ liệu",
        "kỹ sư dữ liệu", "nhà phân tích dữ liệu",
    ], [], 1),
    (6, "AI/ML", [
        "machine learning", "ai engineer", "ai leader", "ai research", "nlp engineer",
        "computer vision", "mlops", "trí tuệ nhân tạo", "ml engineer", "kỹ sư ai",
        "kỹ sư trí tuệ nhân tạo",
    ], ["camera ai", "kinh doanh"], 1),
    (7, "QA/Testing", [
        "tester", " qa ", "qa engineer", "automation test", "performance tester",
        "kiểm thử", "quality assurance",
    ], [], 1),
    (8, "Project/Product Management", [
        "project manager", "product manager", "scrum master", "product owner",
        "business analyst", "quản lý dự án", "phân tích nghiệp vụ",
        "nhà phân tích kinh doanh",
    ], ["marketing", "bán hàng", "sales"], 1),
    (9, "Architecture", [
        "solution architect", "software architect", "enterprise architect",
        "cloud architect", "kiến trúc sư giải pháp", "kiến trúc sư hệ thống",
        "kiến trúc sư phần mềm", "kiến trúc sư web",
    ], [], 1),
    (10, "Networking", [
        "network engineer", "network security engineer", "telecom engineer",
        "voip engineer", "kỹ sư mạng",
    ], [], 1),
    (11, "Cloud Computing", [
        "cloud engineer", "cloud architect", "cloud consultant", "cloud security",
        "aws ", "azure", "đám mây",
    ], ["marketing"], 0),
    (12, "Blockchain & Web3", [
        "blockchain", "smart contract", "solidity", "web3",
    ], ["marketing", "content", "video editor", "affiliate", "giám đốc", "giảng viên"], 0),
    (13, "UI/UX & Design", [
        "ui/ux", "ui designer", "ux designer", "ux researcher", "interaction designer",
        "product designer",
    ], [], 0),
    (14, "ERP/CRM", [
        "sap consultant", "sap fico", "sap fi", "sap mm", "sap abap", "salesforce",
        "odoo", "oracle erp", "erp consultant",
    ], [], 0),
    (15, "IoT & Embedded", [
        "embedded", "firmware", "iot ", "robotics engineer", "kỹ sư nhúng",
        "lập trình nhúng", "hệ thống nhúng", "fpga", "vi mạch",
    ], [], 0),
]

CONTRACT_MAP = {
    "Toàn thời gian": "full_time",
    "Bán thời gian": "part_time",
    "Thực tập": "internship",
    "Thời vụ": "contract",
    "Cộng tác viên": "contract",
    "Khác": "full_time",
}

LOCATION_MAP = {
    "hà nội": "Hà Nội",
    "hồ chí minh": "TP. Hồ Chí Minh",
    "đà nẵng": "Đà Nẵng",
    "hải phòng": "Hải Phòng",
    "cần thơ": "Cần Thơ",
    "nha trang": "Nha Trang",
    "huế": "Huế",
    "hà đông": "Hà Nội",
    "cầu giấy": "Hà Nội",
    "bình thạnh": "TP. Hồ Chí Minh",
    "thủ đức": "TP. Hồ Chí Minh",
    "nam từ liêm": "Hà Nội",
    "quận 7": "TP. Hồ Chí Minh",
}

COMPANY_NAMES = [
    "DataViet Solutions", "Bamboo Software", "Hanoi Cloud Labs", "Saigon Devtech",
    "Indigo Systems", "Northstar IT", "Fintech Wave", "Coral Reef Software",
    "Emerald Data Works", "Falcon Security VN",
]

VN_NUM_RE = re.compile(r"[\'\"]")


def sql_escape(value) -> str:
    if value is None:
        return "null"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def parse_list_field(raw) -> list[str]:
    if not isinstance(raw, str) or not raw.strip():
        return []
    try:
        parsed = literal_eval(raw)
    except (ValueError, SyntaxError):
        return [raw.strip()]
    if isinstance(parsed, list):
        return [str(x).strip() for x in parsed if str(x).strip()]
    return [str(parsed)]


def normalize_location(raw: str) -> str:
    if not isinstance(raw, str) or not raw.strip():
        return "Remote"
    parts = [p.strip() for p in raw.split(",")]
    mapped = [LOCATION_MAP.get(p.lower(), p.title()) for p in parts]
    seen: list[str] = []
    for m in mapped:
        if m not in seen:
            seen.append(m)
    return ", ".join(seen)


def map_employment_type(raw: str) -> str:
    if not isinstance(raw, str):
        return "full_time"
    primary = raw.split(",")[0].strip()
    return CONTRACT_MAP.get(primary, "full_time")


def build_description(row) -> str:
    desc = str(row["description"]).strip() if isinstance(row["description"], str) else ""
    req = str(row["requirements_text"]).strip() if isinstance(row["requirements_text"], str) else ""
    parts = []
    if desc:
        parts.append(desc)
    if req:
        parts.append("Yêu cầu chi tiết: " + req)
    return "\n\n".join(parts) if parts else "Mô tả công việc đang được cập nhật."


def build_requirements(row) -> str | None:
    quals = parse_list_field(row.get("qualifications"))
    skills = parse_list_field(row.get("technical_skills"))
    soft = parse_list_field(row.get("soft_skills"))
    lines = []
    if quals:
        lines.append("- Bằng cấp: " + ", ".join(quals))
    if skills:
        lines.append("- Kỹ năng chuyên môn: " + ", ".join(skills))
    if soft:
        lines.append("- Kỹ năng mềm: " + ", ".join(soft))
    exp = row.get("experience_required")
    if isinstance(exp, str) and exp.strip():
        lines.append("- Kinh nghiệm: " + exp.strip())
    return "\n".join(lines) if lines else None


def build_benefits(row) -> str | None:
    items = parse_list_field(row.get("benefits"))
    return "\n".join(f"- {b}" for b in items) if items else None


def salary_vnd(value) -> str:
    try:
        n = float(value)
    except (TypeError, ValueError):
        return "null"
    if n <= 0:
        return "null"
    return str(int(n * 1_000_000))


def classify(title: str) -> list[int]:
    t = f" {title.lower()} "
    hits = []
    for gid, _name, includes, excludes, _quota in GROUPS:
        if any(ex in t for ex in excludes):
            continue
        if any(inc in t for inc in includes):
            hits.append(gid)
    return hits


def dedup_key(title: str) -> str:
    t = title.lower()
    t = re.sub(r"\(.*?\)", "", t)
    t = re.sub(r"[^a-zà-ỹ0-9 ]", "", t)
    return re.sub(r"\s+", " ", t).strip()


def main() -> None:
    if not CSV_PATH.is_file():
        print(f"CSV file not found: {CSV_PATH}")
        return

    with open(CSV_PATH, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        all_rows = list(reader)

    target_categories = {"công_nghệ_thông_tin_kỹ_thuật_số", "kỹ_thuật_điện_điện_tử_viễn_thông"}
    filtered_rows: list[dict[str, Any]] = []
    for idx, row in enumerate(all_rows):
        if row.get("category", "") not in target_categories:
            continue
        desc = row.get("description") or ""
        req = row.get("requirements_text") or ""
        desc_len = len(desc) + len(req)
        if desc_len <= 120:
            continue
        row["_idx"] = idx
        row["_desc_len"] = desc_len
        filtered_rows.append(row)

    picked_ids: set[int] = set()
    picked_rows: list[tuple[int, str, dict[str, Any]]] = []
    seen_keys: set[str] = set()

    for gid, name, _includes, _excludes, quota in GROUPS:
        candidates = [
            row for row in filtered_rows
            if row["_idx"] not in picked_ids and gid in classify(row.get("job_title", ""))
        ]
        candidates.sort(key=lambda r: r["_desc_len"], reverse=True)

        count = 0
        for row in candidates:
            if count >= quota:
                break
            key = dedup_key(row.get("job_title", ""))
            if key in seen_keys:
                continue
            seen_keys.add(key)
            picked_ids.add(row["_idx"])
            picked_rows.append((gid, name, row))
            count += 1
        print(f"group {gid:2d} {name:<28s} picked {count}/{quota} (pool {len(candidates)})")

    print(f"\ntotal picked: {len(picked_rows)}")

    lines: list[str] = []
    lines.append(BEGIN_MARKER)
    lines.append("-- Real VietJobs IT job postings mapped to the 15 groups in")
    lines.append("-- data_find/data/it-job-categories.md (same taxonomy as")
    lines.append("-- data_find/generated_cv/metadata.csv), for CV<->JD matching evaluation.")
    lines.append("-- Source: data_find/data/vietjobs/VietJobs_full.csv (VietJobs dataset).")
    lines.append("-- Regenerate with: python scripts/build_vietjobs_it_seed.py")
    lines.append("-- Do not hand-edit the rows below — the block gets replaced wholesale.")
    lines.append("--")
    lines.append("-- Uses the recruiter account created earlier in this file as company owner")
    lines.append("-- / job author. Creates its own pool of IT companies, separate from the")
    lines.append("-- 20 companies above.")
    lines.append("")
    lines.append("do $$")
    lines.append("declare")
    lines.append(f"  recruiter_id uuid := '{RECRUITER_ID}';")
    lines.append("  cid uuid;")
    lines.append("  jid uuid;")
    lines.append("  company_ids uuid[] := '{}';")
    lines.append("  company_names text[] := array[")
    company_entries = ",\n".join(f"    {sql_escape(n)}" for n in COMPANY_NAMES)
    lines.append(company_entries)
    lines.append("  ];")
    lines.append("begin")
    lines.append("  for i in 1..array_length(company_names, 1) loop")
    lines.append("    cid := ('f0000000-0000-4000-9000-' || lpad(i::text, 12, '0'))::uuid;")
    lines.append("    insert into public.companies (")
    lines.append("      id, name, slug, website_url, description, created_by_user_id,")
    lines.append("      verification_status, verified_at")
    lines.append("    ) values (")
    lines.append("      cid, company_names[i],")
    lines.append("      regexp_replace(lower(company_names[i]), '[^a-z0-9]+', '-', 'g') || '-vj',")
    lines.append("      'https://example.com/vj-' || i::text,")
    lines.append("      'Công ty CNTT (seed VietJobs) #' || i::text || ' — ' || company_names[i],")
    lines.append("      recruiter_id, 'verified', now() - ((i % 20) || ' days')::interval")
    lines.append("    )")
    lines.append("    on conflict (id) do nothing;")
    lines.append("    insert into public.company_members (company_id, user_id, role, is_active)")
    lines.append("    values (cid, recruiter_id, 'owner', true)")
    lines.append("    on conflict (company_id, user_id) do nothing;")
    lines.append("    company_ids := array_append(company_ids, cid);")
    lines.append("  end loop;")
    lines.append("")

    for i, (gid, gname, row) in enumerate(picked_rows, start=1):
        jid_uuid = uuid.uuid5(NAMESPACE, f"vietjobs-it:{i}")
        company_idx = ((i - 1) % len(COMPANY_NAMES)) + 1
        title = str(row["job_title"]).strip()
        description = build_description(row)
        requirements = build_requirements(row)
        benefits = build_benefits(row)
        location = normalize_location(row["location"])
        emp_type = map_employment_type(row["contract_type"])
        smin = salary_vnd(row.get("salary_min"))
        smax = salary_vnd(row.get("salary_max"))

        lines.append(f"  -- [{i}/{len(picked_rows)}] group {gid} ({gname}): {title}")
        lines.append(f"  jid := '{jid_uuid}'::uuid;")
        lines.append(f"  cid := company_ids[{company_idx}];")
        lines.append("  insert into public.job_posts (")
        lines.append("    id, company_id, created_by_user_id, title, description, requirements,")
        lines.append("    benefits, location, employment_type, salary_min, salary_max, currency,")
        lines.append("    status, published_at, deadline_at")
        lines.append("  ) values (")
        lines.append(f"    jid, cid, recruiter_id, {sql_escape(title)},")
        lines.append(f"    {sql_escape(description)},")
        lines.append(f"    {sql_escape(requirements)},")
        lines.append(f"    {sql_escape(benefits)},")
        lines.append(f"    {sql_escape(location)}, '{emp_type}'::public.employment_type,")
        lines.append(f"    {smin}, {smax}, 'VND', 'published',")
        lines.append(f"    now() - (({i} % 21) || ' days')::interval,")
        lines.append(f"    now() + ((20 + ({i} % 45)) || ' days')::interval")
        lines.append("  )")
        lines.append("  on conflict (id) do nothing;")
        lines.append("")

    lines.append("end $$;")
    block = "\n".join(lines) + "\n" + END_MARKER + "\n"

    seed_text = SEED_PATH.read_text(encoding="utf-8")
    marker_re = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n?",
        re.DOTALL,
    )
    if marker_re.search(seed_text):
        seed_text = marker_re.sub(block, seed_text)
    else:
        seed_text = seed_text.rstrip("\n") + "\n\n" + block

    SEED_PATH.write_text(seed_text, encoding="utf-8")
    print(f"\nmerged into {SEED_PATH} ({len(picked_rows)} job_posts)")


if __name__ == "__main__":
    main()
