"""Production Seed Revert (Rollback) Script.

Reads a manifest JSON file (`scripts/seed_manifest.json` generated by `seed_production.py`)
and cleanly removes ALL seeded data and Storage files in exact reverse dependency order.

This guarantees immediate reversion of the sample seed step on Production/Staging/Local
WITHOUT affecting real live production users or non-seeded data.

Usage:
    python scripts/revert_production_seed.py --url <SUPABASE_URL> --key <SERVICE_ROLE_KEY>
Or set environment variables SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from supabase import create_client

DEFAULT_MANIFEST_PATH = ROOT / "scripts" / "seed_manifest.json"


def main():
    from dotenv import load_dotenv
    load_dotenv(ROOT / ".env")

    parser = argparse.ArgumentParser(description="Revert seeded data on Supabase using manifest.")
    parser.add_argument("--url", help="Supabase API URL", default=os.getenv("SUPABASE_URL"))
    parser.add_argument("--key", help="Supabase Service Role Key", default=os.getenv("SUPABASE_SERVICE_ROLE_KEY"))
    parser.add_argument("--manifest", help="Manifest JSON file path", default=str(DEFAULT_MANIFEST_PATH))
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"ERROR: Manifest file not found at '{manifest_path.resolve()}'.")
        print("Nothing to revert or seed manifest was already cleaned up.")
        sys.exit(1)

    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    url = args.url or manifest.get("supabase_url")
    key = args.key or os.getenv("SUPABASE_SERVICE_ROLE_KEY")

    if not url or not key:
        print("ERROR: Supabase URL and Service Role Key are required.")
        print("Provide --url and --key or set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY env vars.")
        sys.exit(1)

    print(f"Connecting to Supabase instance: {url}")
    print(f"Reading manifest file created at: {manifest.get('created_at', 'unknown')}")
    client = create_client(url, key)

    deleted_counts = {}

    try:
        # 1. Delete Storage Files
        storage_paths = manifest.get("storage_paths", [])
        if storage_paths:
            print(f"\n[1/9] Removing {len(storage_paths)} storage files from bucket 'resumes'...")
            try:
                client.storage.from_("resumes").remove(storage_paths)
                deleted_counts["storage_files"] = len(storage_paths)
            except Exception as e:
                print(f"  Warning deleting storage files: {e}")

        # 2. Delete Vector Embeddings
        resume_ids = manifest.get("resume_ids", [])
        if resume_ids:
            print(f"\n[2/9] Deleting embedded resumes for {len(resume_ids)} resumes...")
            try:
                res = client.table("embedded_resumes").delete().in_("resume_id", resume_ids).execute()
                deleted_counts["embedded_resumes"] = len(resume_ids)
            except Exception as e:
                print(f"  Warning deleting embedded resumes: {e}")

        # 3. Delete Job Submissions
        submit_ids = manifest.get("submit_ids", [])
        resume_ids = manifest.get("resume_ids", [])
        job_ids = manifest.get("job_ids", [])
        if submit_ids or resume_ids or job_ids:
            print(f"\n[3/9] Deleting job submissions...")
            try:
                if submit_ids:
                    client.table("job_submits").delete().in_("id", submit_ids).execute()
                if resume_ids:
                    client.table("job_submits").delete().in_("resume_id", resume_ids).execute()
                if job_ids:
                    client.table("job_submits").delete().in_("job_post_id", job_ids).execute()
                deleted_counts["job_submits"] = len(submit_ids)
            except Exception as e:
                print(f"  Warning deleting job submissions: {e}")

        # 4. Delete Resumes
        if resume_ids:
            print(f"\n[4/9] Deleting {len(resume_ids)} resumes...")
            try:
                client.table("resumes").delete().in_("id", resume_ids).execute()
                deleted_counts["resumes"] = len(resume_ids)
            except Exception as e:
                print(f"  Warning deleting resumes: {e}")

        # 5. Delete Job Posts
        company_ids = manifest.get("company_ids", [])
        if job_ids or company_ids:
            print(f"\n[5/9] Deleting job posts...")
            try:
                if job_ids:
                    client.table("job_posts").delete().in_("id", job_ids).execute()
                if company_ids:
                    client.table("job_posts").delete().in_("company_id", company_ids).execute()
                deleted_counts["job_posts"] = len(job_ids)
            except Exception as e:
                print(f"  Warning deleting job posts: {e}")

        # 6. Delete Company Members
        if company_ids:
            print(f"\n[6/9] Deleting company members for {len(company_ids)} companies...")
            try:
                client.table("company_members").delete().in_("company_id", company_ids).execute()
                deleted_counts["company_members"] = len(company_ids)
            except Exception as e:
                print(f"  Warning deleting company members: {e}")

        # 7. Delete Companies
        if company_ids:
            print(f"\n[7/9] Deleting {len(company_ids)} companies...")
            try:
                client.table("companies").delete().in_("id", company_ids).execute()
                deleted_counts["companies"] = len(company_ids)
            except Exception as e:
                print(f"  Warning deleting companies: {e}")

        # 8. Delete Profiles
        profile_ids = manifest.get("profile_ids", [])
        user_ids = manifest.get("user_ids", [])
        all_profile_uids = list(set(profile_ids + user_ids))
        if all_profile_uids:
            print(f"\n[8/9] Deleting profiles for {len(all_profile_uids)} users...")
            try:
                client.table("profiles").delete().in_("id", all_profile_uids).execute()
                deleted_counts["profiles"] = len(all_profile_uids)
            except Exception as e:
                print(f"  Warning deleting profiles: {e}")

        # 9. Delete Auth Users
        if user_ids:
            print(f"\n[9/9] Deleting {len(user_ids)} auth users via Admin API...")
            count_users_deleted = 0
            for uid in user_ids:
                try:
                    client.auth.admin.delete_user(uid)
                    count_users_deleted += 1
                except Exception as u_err:
                    print(f"  Warning deleting user {uid}: {u_err}")
            deleted_counts["auth_users"] = count_users_deleted

        # Rename manifest file to archive it
        timestamp_str = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        reverted_manifest_path = manifest_path.with_name(f"seed_manifest_reverted_{timestamp_str}.json")
        manifest_path.rename(reverted_manifest_path)

        print("\n========================================================")
        print(" SUCCESS: Production Seed Reverted Cleanly!")
        print(" Summary of deleted seeded entities:")
        for k, v in deleted_counts.items():
            print(f"  - {k}: {v}")
        print(f" Manifest archived to: {reverted_manifest_path.resolve()}")
        print("========================================================")

    except Exception as e:
        print(f"\nERROR during revert process: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
