"""Append synthetic generated_cv resumes + job_submits into supabase/seed.sql.

Reads data_find/generated_cv/metadata.csv (synthetic IT CVs across the same
15 groups as scripts/build_vietjobs_it_seed.py), and for the first 15 CVs of
each of the 10 groups that have a VIETJOBS-IT-SEED job_post (groups 11-15 are
skipped -- build_vietjobs_it_seed.py no longer creates job_posts for them):

- creates a candidate auth user (password123, like every other seed account)
- inserts a `resumes` row (metadata only -- storage_path points to where the
  PDF will live; PDF bytes are rendered and uploaded separately, see below)
- inserts a `job_submits` row linking the resume to that group's single real
  VietJobs job_post (from the ids scripts/build_vietjobs_it_seed.py already
  wrote into seed.sql's VIETJOBS-IT-SEED block)
- every 3rd seeded row also gets an extra `application_stages` row, cycling
  through screening/interview/offer/rejected, so the demo pipeline shows
  more than just "pending"

One designated CV (CANDIDATE_OVERRIDE_CV_ID, in the Software Development
group) is attached to the fixed candidate@example.com login instead of a new
synthetic user, so that account has one real application to inspect.

This corpus doubles as the demo application pool for CV<->JD matching:
public.match_resumes_for_job joins embedded_resumes through job_submits, so
a resume with no job_submits row is invisible to recruiter-side matching.

Also copies each selected CV's markdown source (small, ~3KB, and NOT
gitignored like data_find/) into supabase/seed_assets/cvs/<cv_id>.md, and
writes supabase/seed_assets/cvs/manifest.json mapping each CV to the ids/
paths scripts/seed_upload_generated_cvs.py needs to actually upload the PDF
bytes later, in any environment (no dependency on data_find/ at seed/deploy
time).

Writes a `-- === BEGIN GENERATED-CV-SEED ... === / END` block directly into
supabase/seed.sql, replacing any previous run's block wholesale. Runs
automatically with `supabase db reset` -- no separate apply step for the SQL
rows themselves (the PDF bytes still need a separate upload step -- see
scripts/seed_upload_generated_cvs.py).

    python scripts/seed_generated_cvs.py [--limit N]
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scripts.cv_markdown import parse_front_matter, render_markdown_to_pdf  # noqa: E402

CV_ROOT = ROOT / "data_find" / "generated_cv"
METADATA_CSV = CV_ROOT / "metadata.csv"
SEED_PATH = ROOT / "supabase" / "seed.sql"
ASSETS_DIR = ROOT / "supabase" / "seed_assets" / "cvs"

BEGIN_MARKER = "-- === BEGIN GENERATED-CV-SEED (generated by scripts/seed_generated_cvs.py) ==="
END_MARKER = "-- === END GENERATED-CV-SEED ==="

VIETJOBS_BEGIN = "-- === BEGIN VIETJOBS-IT-SEED (generated by scripts/build_vietjobs_it_seed.py) ==="
VIETJOBS_END = "-- === END VIETJOBS-IT-SEED ==="

NAMESPACE = uuid.UUID("6f6d1e2a-6c0a-4c7b-8d0e-2a6b1f0c5a11")
EMAIL_DOMAIN = "seed.local"

CANDIDATE_ID = uuid.UUID("11111111-1111-1111-1111-111111111111")
RECRUITER_ID = "22222222-2222-2222-2222-222222222222"
CANDIDATE_OVERRIDE_CV_ID = "G1-BE-01"

MAX_PER_GROUP = 15
STAGE_CYCLE = ("screening", "interview", "offer", "rejected")

JOB_ID_RE = re.compile(
    r"-- \[\d+/\d+\] group (?P<gid>\d+) \([^)]*\):.*?\n\s*jid := '(?P<jid>[0-9a-fA-F-]{36})'::uuid;",
    re.DOTALL,
)


def sql_escape(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def user_id_for(cv_id: str) -> uuid.UUID:
    return uuid.uuid5(NAMESPACE, f"user:{cv_id}")


def resume_id_for(cv_id: str) -> uuid.UUID:
    return uuid.uuid5(NAMESPACE, f"resume:{cv_id}")


def submit_id_for(cv_id: str) -> uuid.UUID:
    return uuid.uuid5(NAMESPACE, f"submit:{cv_id}")


def load_job_ids_by_group(seed_text: str) -> dict[int, list[str]]:
    start = seed_text.index(VIETJOBS_BEGIN)
    end = seed_text.index(VIETJOBS_END, start)
    block = seed_text[start:end]
    jobs: dict[int, list[str]] = {}
    for m in JOB_ID_RE.finditer(block):
        jobs.setdefault(int(m.group("gid")), []).append(m.group("jid"))
    return jobs


def build_block(
    rows: list[dict], job_ids_by_group: dict[int, list[str]]
) -> tuple[list[str], list[dict], int]:
    lines = [
        BEGIN_MARKER,
        "-- Synthetic IT resumes (data_find/generated_cv/metadata.csv) seeded as",
        "-- candidate accounts + job_submits against the VIETJOBS-IT-SEED job_posts",
        "-- above (same group), capped at 15 CVs per group, so they act as the demo",
        "-- application pool for CV<->JD matching (match_resumes_for_job joins",
        "-- through job_submits). PDF bytes are rendered from the markdown copied",
        "-- into supabase/seed_assets/cvs/ and uploaded separately -- see",
        "-- scripts/seed_upload_generated_cvs.py.",
        "-- Regenerate with: python scripts/seed_generated_cvs.py",
        "-- Do not hand-edit the rows below -- the block gets replaced wholesale.",
        "",
    ]
    group_counters: dict[int, int] = {}
    manifest: list[dict] = []
    seeded = 0
    skipped_missing_md = 0
    skipped_no_jobs = 0
    skipped_group_full = 0

    if ASSETS_DIR.exists():
        shutil.rmtree(ASSETS_DIR)
    ASSETS_DIR.mkdir(parents=True)

    for row in rows:
        cv_id = row["cv_id"]
        md_rel = row["md_path"].strip()
        md_path = CV_ROOT / md_rel if md_rel else None
        if md_path is None or not md_path.is_file():
            skipped_missing_md += 1
            continue

        gid = int(row["group_id"])
        job_ids = job_ids_by_group.get(gid)
        if not job_ids:
            skipped_no_jobs += 1
            continue

        count_so_far = group_counters.get(gid, 0)
        if count_so_far >= MAX_PER_GROUP:
            skipped_group_full += 1
            continue
        job_id = job_ids[count_so_far % len(job_ids)]
        group_counters[gid] = count_so_far + 1

        uid = CANDIDATE_ID if cv_id == CANDIDATE_OVERRIDE_CV_ID else user_id_for(cv_id)
        rid = resume_id_for(cv_id)
        sid = submit_id_for(cv_id)
        email = f"{cv_id.lower()}@{EMAIL_DOMAIN}"
        full_name = row["candidate_name"]
        title = row["target_role"]
        filename = f"{cv_id.lower()}.pdf"
        storage_path = f"{uid}/resumes/{rid}/{filename}"

        md_text = md_path.read_text(encoding="utf-8")
        _metadata, body = parse_front_matter(md_text)
        pdf_bytes = render_markdown_to_pdf(body)
        size_bytes = len(pdf_bytes)
        shutil.copyfile(md_path, ASSETS_DIR / f"{cv_id}.md")

        lines.append(f"-- {cv_id} (group {gid} {row['group_name']} / {row['subgroup']}): {title}")
        lines.append("insert into auth.users (")
        lines.append("  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,")
        lines.append("  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,")
        lines.append("  confirmation_token, email_change, email_change_token_new, recovery_token")
        lines.append(") values (")
        lines.append(f"  '00000000-0000-0000-0000-000000000000', '{uid}',")
        lines.append(
            f"  'authenticated', 'authenticated', {sql_escape(email)}, "
            "crypt('password123', gen_salt('bf')), now(),"
        )
        lines.append("  '{\"provider\":\"email\",\"providers\":[\"email\"]}'::jsonb,")
        lines.append(f"  jsonb_build_object('full_name', {sql_escape(full_name)}),")
        lines.append("  now(), now(), '', '', '', ''")
        lines.append(")")
        lines.append("on conflict (id) do nothing;")
        lines.append("")

        lines.append("insert into auth.identities (")
        lines.append(
            "  id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at"
        )
        lines.append(") values (")
        lines.append(f"  gen_random_uuid(), '{uid}',")
        lines.append(f"  jsonb_build_object('sub', '{uid}'::text, 'email', {sql_escape(email)}),")
        lines.append(f"  'email', '{uid}'::text, now(), now(), now()")
        lines.append(")")
        lines.append("on conflict do nothing;")
        lines.append("")

        lines.append("insert into public.resumes (")
        lines.append("  id, user_id, bucket_id, storage_path, original_filename, title,")
        lines.append("  mime_type, size_bytes, is_default")
        lines.append(") values (")
        lines.append(f"  '{rid}', '{uid}', 'resumes',")
        lines.append(f"  {sql_escape(storage_path)},")
        lines.append(f"  {sql_escape(filename)},")
        lines.append(f"  {sql_escape(title)},")
        lines.append(f"  'application/pdf', {size_bytes}, true")
        lines.append(")")
        lines.append("on conflict (id) do nothing;")
        lines.append("")

        lines.append("insert into public.job_submits (")
        lines.append("  id, job_post_id, applicant_user_id, resume_id, cover_letter")
        lines.append(") values (")
        lines.append(f"  '{sid}', '{job_id}', '{uid}', '{rid}',")
        lines.append(f"  {sql_escape('Cover letter -- ' + title)}")
        lines.append(")")
        lines.append("on conflict (job_post_id, applicant_user_id) do nothing;")
        lines.append("")

        seeded += 1
        if seeded % 3 == 0:
            stage = STAGE_CYCLE[(seeded // 3 - 1) % len(STAGE_CYCLE)]
            lines.append("insert into public.application_stages (")
            lines.append("  application_id, changed_by_user_id, stage, note, is_system_generated")
            lines.append(") values (")
            lines.append(f"  '{sid}', '{RECRUITER_ID}', '{stage}'::public.application_status,")
            lines.append(f"  'Seed pipeline {stage}', false")
            lines.append(");")
            lines.append("")

        manifest.append(
            {
                "cv_id": cv_id,
                "user_id": str(uid),
                "resume_id": str(rid),
                "job_post_id": job_id,
                "storage_path": storage_path,
                "original_filename": filename,
                "title": title,
            }
        )

    candidate_job_id = next(
        (m["job_post_id"] for m in manifest if m["cv_id"] == CANDIDATE_OVERRIDE_CV_ID), None
    )
    saved_job_ids = sorted({ids[0] for ids in job_ids_by_group.values()})
    saved_job_ids = [jid for jid in saved_job_ids if jid != candidate_job_id][:3]
    if saved_job_ids:
        lines.append("insert into public.saved_jobs (user_id, job_post_id) values")
        lines.append(",\n".join(f"  ('{CANDIDATE_ID}', '{jid}')" for jid in saved_job_ids))
        lines.append("on conflict (user_id, job_post_id) do nothing;")
        lines.append("")

    lines.append(END_MARKER)
    print(
        f"seeded {seeded} CVs across {len(group_counters)} groups "
        f"(skipped {skipped_missing_md} missing markdown, {skipped_no_jobs} no job pool for group, "
        f"{skipped_group_full} over the {MAX_PER_GROUP}/group cap)"
    )
    return lines, manifest, seeded


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=None, help="only process the first N metadata rows")
    args = parser.parse_args()

    seed_text = SEED_PATH.read_text(encoding="utf-8")
    if VIETJOBS_BEGIN not in seed_text:
        raise SystemExit("VIETJOBS-IT-SEED block not found -- run scripts/build_vietjobs_it_seed.py first")
    job_ids_by_group = load_job_ids_by_group(seed_text)
    missing_groups = [g for g in range(1, 11) if g not in job_ids_by_group]
    if missing_groups:
        print(f"warning: no VietJobs job_posts for groups {missing_groups}")

    with METADATA_CSV.open(encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))
    if args.limit:
        rows = rows[: args.limit]

    lines, manifest, seeded = build_block(rows, job_ids_by_group)
    block = "\n".join(lines) + "\n"

    marker_re = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n?", re.DOTALL)
    if marker_re.search(seed_text):
        seed_text = marker_re.sub(block, seed_text)
    else:
        seed_text = seed_text.rstrip("\n") + "\n\n" + block

    SEED_PATH.write_text(seed_text, encoding="utf-8")

    manifest_path = ASSETS_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"merged into {SEED_PATH} ({seeded} resumes + job_submits)")
    print(f"wrote {len(manifest)} markdown CVs + manifest to {ASSETS_DIR}")


if __name__ == "__main__":
    main()
