"""Tests for candidate anonymization module."""

from __future__ import annotations

from backend.app.services.matching.anonymize import (
    anonymize_candidates,
    deanonymize_candidates,
    deanonymize_reasons,
)


def _candidate(
    app_id: str,
    user_id: str,
    *,
    full_name: str | None = None,
    email: str | None = None,
) -> dict:
    return {
        "application_id": app_id,
        "applicant_user_id": user_id,
        "full_name": full_name,
        "email": email,
        "skills": ["python"],
        "clean_markdown": "Some PII-free content",
    }


def test_anonymize_candidates_creates_sequential_ids():
    result = anonymize_candidates([
        _candidate("app1", "user1", full_name="Alice", email="alice@example.com"),
        _candidate("app2", "user2", full_name="Bob", email="bob@example.com"),
    ])

    assert len(result.id_map) == 2
    assert "CAND_001" in result.id_map
    assert "CAND_002" in result.id_map

    # Candidates list has anonymous IDs
    assert result.candidates[0]["_anon_id"] == "CAND_001"
    assert result.candidates[1]["_anon_id"] == "CAND_002"

    # Original IDs NOT in candidates (PII safety)
    assert result.candidates[0].get("application_id") == "app1"
    # _anon_id is added but application_id is still there as we copy the row
    assert "_anon_id" in result.candidates[0]


def test_anonymize_candidates_strips_pii():
    result = anonymize_candidates([
        _candidate("app1", "user1", full_name="Alice", email="alice@example.com"),
    ])

    # id_map stores the real PII
    assert result.id_map["CAND_001"].full_name == "Alice"
    assert result.id_map["CAND_001"].email == "alice@example.com"

    # Candidates list should have PII removed
    anon_candidate = result.candidates[0]
    assert anon_candidate.get("full_name") is None
    assert anon_candidate.get("email") is None


def test_deanonymize_reasons_maps_back_correctly():
    result = anonymize_candidates([
        _candidate("app1", "user1"),
        _candidate("app2", "user2"),
    ])

    # Simulate LLM returning anonymous IDs
    llm_reasons = {
        "CAND_001": "Khớp Python tốt",
        "CAND_002": "Có kinh nghiệm FastAPI",
    }

    reasons = deanonymize_reasons(llm_reasons, result.id_map)

    assert reasons == {
        "app1": "Khớp Python tốt",
        "app2": "Có kinh nghiệm FastAPI",
    }


def test_deanonymize_reasons_ignores_unknown_ids():
    result = anonymize_candidates([
        _candidate("app1", "user1"),
    ])

    llm_reasons = {
        "CAND_001": "ok",
        "CAND_999": "should be ignored",
    }

    reasons = deanonymize_reasons(llm_reasons, result.id_map)

    assert "app1" in reasons
    assert "CAND_999" not in reasons
    assert "CAND_001" not in reasons  # Only real IDs as keys


def test_deanonymize_candidates_restores_identities():
    result = anonymize_candidates([
        _candidate("app1", "user1", full_name="Alice", email="alice@example.com"),
        _candidate("app2", "user2", full_name="Bob", email="bob@example.com"),
    ])

    # Simulate some LLM processing that adds a field
    for cand in result.candidates:
        cand["match_reason"] = "Generated by LLM"
        cand.pop("full_name", None)
        cand.pop("email", None)

    restored = deanonymize_candidates(result.candidates, result.id_map)

    assert restored[0]["application_id"] == "app1"
    assert restored[0]["full_name"] == "Alice"
    assert restored[0]["email"] == "alice@example.com"
    assert restored[0]["match_reason"] == "Generated by LLM"
    assert "_anon_id" not in restored[0]

    assert restored[1]["application_id"] == "app2"
    assert restored[1]["full_name"] == "Bob"


def test_deanonymize_candidates_handles_missing_mapping():
    # Candidate without _anon_id
    candidates = [{"match_reason": "ok"}]
    id_map = {}

    restored = deanonymize_candidates(candidates, id_map)

    # Should return unchanged candidates
    assert restored[0]["match_reason"] == "ok"


def test_empty_candidates_returns_empty():
    result = anonymize_candidates([])
    assert result.candidates == []
    assert result.id_map == {}


def test_anonymization_preserves_other_fields():
    original = _candidate("app1", "user1")
    original["skills"] = ["python", "fastapi"]
    original["clean_markdown"] = "Some content"
    original["rrf_score"] = 0.95
    original["rerank_score"] = 0.8

    result = anonymize_candidates([original])

    anon = result.candidates[0]
    assert anon["skills"] == ["python", "fastapi"]
    assert anon["clean_markdown"] == "Some content"
    assert anon["rrf_score"] == 0.95
    assert anon["rerank_score"] == 0.8
